### ISSUE TITLE
opengl issure

### ISSUE THREAD

**Issue by mzgsxs** [osrf/docker_images#105]
By running the following:
http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration
I got
`...
setting /run_id to 29647c82-ee3c-11e7-a9cd-aced5c48ed97
process[rosout-1]: started with pid [63]
started core service [/rosout]
libGL error: failed to load driver: swrast
libGL error: failed to load driver: swrast
rviz::RenderSystem: error creating render window: std::exception
[ WARN] [1514732782.911415394]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038)
...
rviz::RenderSystem: error creating render window: std::exception
[ WARN] [1514732782.914703833]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038)
rviz::RenderSystem: error creating render window: std::exception
[ERROR] [1514732782.914770791]: Unable to create the rendering window after 100 tries.
[ INFO] [1514732782.914796125]: Stereo is NOT SUPPORTED
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
bash: line 1:    32 Aborted                 (core dumped) rosrun rviz rviz
`
Which I have no clue why?
with
##+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P0    N/A /  N/A |   1778MiB /  4041MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1233      G   /usr/lib/xorg/Xorg                           979MiB |
|    0      2747      G   compiz                                       425MiB |
|    0      3122      G   ...-token=6366745CBCD8230114E9546C5578A132   372MiB |
+-----------------------------------------------------------------------------+

Docker version 17.12.0-ce, build c97c6d6
Nvidia-docker version2

Ive spend my last whole day of 2017 trying to solve this, it just doesn't work tho
Thanks!

**Comment by mzgsxs** [comment]
ok, solve by using nvidia-docker V1

**Comment by ruffsl** [comment]
My guess is that its because nvidia-docker v2 no longer mounts all the all driver libraries by default for you. Looks like you might have to set `NVIDIA_DRIVER_CAPABILITIES` accordingly. From Nvidia's wiki:
* [Are my container images built for version 1.0 compatible with 2.0?](https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#are-my-container-images-built-for-version-10-compatible-with-20)
* [Environment variables (OCI spec)](https://github.com/nvidia/nvidia-container-runtime#environment-variables-oci-spec)
* [Dockerfile ENV Example](https://gitlab.com/nvidia/cuda/blob/17c965bec070ce2bd50e9db79563e851b69d1a62/9.0/base/Dockerfile#L32)

Perhaps if that works, you could update the ROS wiki accordingly?

**Comment by ruffsl** [comment]
I'm going to close this now.
Also, as an FYI. Looks like nvidia as released beta images for OpenGL support:
https://github.com/NVIDIA/nvidia-docker/issues/11#issuecomment-356802940

**Comment by nju044** [comment]
> By running the following:
> http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration
> I got
> `... setting /run_id to 29647c82-ee3c-11e7-a9cd-aced5c48ed97 process[rosout-1]: started with pid [63] started core service [/rosout] libGL error: failed to load driver: swrast libGL error: failed to load driver: swrast rviz::RenderSystem: error creating render window: std::exception [ WARN] [1514732782.911415394]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038) ... rviz::RenderSystem: error creating render window: std::exception [ WARN] [1514732782.914703833]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038) rviz::RenderSystem: error creating render window: std::exception [ERROR] [1514732782.914770791]: Unable to create the rendering window after 100 tries. [ INFO] [1514732782.914796125]: Stereo is NOT SUPPORTED terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_S_construct null not valid bash: line 1: 32 Aborted (core dumped) rosrun rviz rviz `
> Which I have no clue why?
> with
> ##+-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.90 Driver Version: 384.90 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce GTX 1050 Off | 00000000:01:00.0 Off | N/A |
> | N/A 41C P0 N/A / N/A | 1778MiB / 4041MiB | 4% Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> | 0 1233 G /usr/lib/xorg/Xorg 979MiB |
> | 0 2747 G compiz 425MiB |
> | 0 3122 G ...-token=6366745CBCD8230114E9546C5578A132 372MiB |
> +-----------------------------------------------------------------------------+
> 
> Docker version 17.12.0-ce, build c97c6d6
> Nvidia-docker version2
> 
> Ive spend my last whole day of 2017 trying to solve this, it just doesn't work tho
> Thanks!

Hi mzgsxs,
I know this issue is closed, but could you please help me with this issue?
My host OS is ubuntu 16.04, and docker OS is ubuntu 14.04.
GPU is GeForce GTX 1070, using "NVDIA binary driver-version 384.130 from nvidia-384 (proprietary, tested)".
nvidia-modprobe and nvidia-docker are installed on host(ubuntu 16.04), referring to [https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-1.0)].

In docker OS(ubuntu 14.04), when running `rosrun rviz rviz`, following errors occur:
`[ INFO] [1554895474.061609183]: rviz version 1.11.19
[ INFO] [1554895474.061687744]: compiled against Qt version 4.8.6
[ INFO] [1554895474.061718795]: compiled against OGRE version 1.8.1 (Byatis)
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x9c00003
libGL error: failed to load driver: swrast
libGL error: failed to load driver: swrast
rviz::RenderSystem: error creating render window: std::exception
[ WARN] [1554895474.179156185]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038)
...
[ERROR] [1554895474.185641232]: Unable to create the rendering window after 100 tries.
[ INFO] [1554895474.185674457]: Stereo is NOT SUPPORTED
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
`

This is exactly same as your issue, but I couldn't solve it. Can you help me with it?

**Comment by mzgsxs** [comment]
> > By running the following:
> > http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration
> > I got
> > `... setting /run_id to 29647c82-ee3c-11e7-a9cd-aced5c48ed97 process[rosout-1]: started with pid [63] started core service [/rosout] libGL error: failed to load driver: swrast libGL error: failed to load driver: swrast rviz::RenderSystem: error creating render window: std::exception [ WARN] [1514732782.911415394]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038) ... rviz::RenderSystem: error creating render window: std::exception [ WARN] [1514732782.914703833]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038) rviz::RenderSystem: error creating render window: std::exception [ERROR] [1514732782.914770791]: Unable to create the rendering window after 100 tries. [ INFO] [1514732782.914796125]: Stereo is NOT SUPPORTED terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_S_construct null not valid bash: line 1: 32 Aborted (core dumped) rosrun rviz rviz `
> > Which I have no clue why?
> > with
> > ##+-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 384.90 Driver Version: 384.90 |
> > |-------------------------------+----------------------+----------------------+
> > | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> > | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> > |===============================+======================+======================|
> > | 0 GeForce GTX 1050 Off | 00000000:01:00.0 Off | N/A |
> > | N/A 41C P0 N/A / N/A | 1778MiB / 4041MiB | 4% Default |
> > +-------------------------------+----------------------+----------------------+
> > +-----------------------------------------------------------------------------+
> > | Processes: GPU Memory |
> > | GPU PID Type Process name Usage |
> > |=============================================================================|
> > | 0 1233 G /usr/lib/xorg/Xorg 979MiB |
> > | 0 2747 G compiz 425MiB |
> > | 0 3122 G ...-token=6366745CBCD8230114E9546C5578A132 372MiB |
> > +-----------------------------------------------------------------------------+
> > Docker version 17.12.0-ce, build c97c6d6
> > Nvidia-docker version2
> > Ive spend my last whole day of 2017 trying to solve this, it just doesn't work tho
> > Thanks!
> 
> Hi mzgsxs,
> I know this issue is closed, but could you please help me with this issue?
> My host OS is ubuntu 16.04, and docker OS is ubuntu 14.04.
> GPU is GeForce GTX 1070, using "NVDIA binary driver-version 384.130 from nvidia-384 (proprietary, tested)".
> nvidia-modprobe and nvidia-docker are installed on host(ubuntu 16.04), referring to [https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-1.0)].
> 
> In docker OS(ubuntu 14.04), when running `rosrun rviz rviz`, following errors occur:
> `[ INFO] [1554895474.061609183]: rviz version 1.11.19 [ INFO] [1554895474.061687744]: compiled against Qt version 4.8.6 [ INFO] [1554895474.061718795]: compiled against OGRE version 1.8.1 (Byatis) X Error: BadAccess (attempt to access private resource denied) 10 Extension: 130 (MIT-SHM) Minor opcode: 1 (X_ShmAttach) Resource id: 0x9c00003 libGL error: failed to load driver: swrast libGL error: failed to load driver: swrast rviz::RenderSystem: error creating render window: std::exception [ WARN] [1554895474.179156185]: OGRE EXCEPTION(2:InvalidParametersException): Window with name 'OgreWindow(0)' already exists in GLRenderSystem::_createRenderWindow at /build/buildd/ogre-1.8-1.8.1+dfsg/RenderSystems/GL/src/OgreGLRenderSystem.cpp (line 1038) ... [ERROR] [1554895474.185641232]: Unable to create the rendering window after 100 tries. [ INFO] [1554895474.185674457]: Stereo is NOT SUPPORTED terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_S_construct null not valid Aborted (core dumped) `
> 
> This is exactly same as your issue, but I couldn't solve it. Can you help me with it?

Could you please include the commands for starting the docker image?
it should be something like this in the terminal:

xhost -local:root

NV_GPU='0' nvidia-docker run -it \
--net=host \
--env="DISPLAY" \
--env="QT_X11_NO_MITSHM=1" \
--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
--volume="/$HOME/.Xauthority:/root/.Xauthority:rw" \
--shm-size=1g \
--ulimit memlock=-1 \
YOUR_DOCKER_IMAGE

xhost -local:root
