### ISSUE TITLE
Ubuntu Zesty is EOL

### ISSUE THREAD

**Issue by tianon** [osrf/docker_images#111]
The base image used by `ros:lunar-ros-core-zesty` (`ubuntu:zesty`) is now EOL and unsupported as of https://github.com/docker-library/official-images/pull/3901, and as such `ros:lunar-ros-core-zesty` should be either updated or removed. :+1:

**Comment by mikaelarguedas** [comment]
Thanks @tianon for the heads up,
I'm planning on removing them (https://github.com/osrf/docker_images/pull/110) and submitting the corresponding patch upstream soon
