### ISSUE TITLE
ROS2 | sourcing autocomplete

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#114]
Context: https://github.com/osrf/docker_images/pull/113#issuecomment-360911973

Perhaps it would be nice to leverage ros2 CLI autocompletion within the container. This would entail sourcing the necessary setup files within the entry point, or just providing an additional entrypoint script to optimally do so.

**Comment by mikaelarguedas** [comment]
This has now been fixed upstream https://github.com/ros2/ros2cli/pull/84.
I'll wait until a deb for ardent has been released with that change to close this issue

**Comment by dirk-thomas** [comment]
If it works in the case when installing the Debian packages and then sourcing the setup file on a native system (or in a Docker doing it interactively) the problem seems to be not related to the released packages and the logic in the setup files. I don't have any idea why it would behave differently in the Dockerfile.

**Comment by ruffsl** [comment]
@mikaelarguedas , I just built the ros2 ardent images locally with the makefile and observed the same autocomplete issue, i.e. only works after I source the setup script manually afterwards.

https://docs.docker.com/engine/reference/builder/#entrypoint

I tried overriding the default entrypoint through the run cli, but it seems that the second bash session is not inheriting the environments set by the setup as expected:

``` shell
docker run -it --entrypoint "/bin/bash" osrf/ros2:ardent-full -c "source '/opt/ros/ardent/setup.bash' && bash"
```

**Comment by dirk-thomas** [comment]
I don't think a shell created *after* sourcing is supposed to "inherit" the completion.

**Comment by ruffsl** [comment]
> I don't think a shell created after sourcing is supposed to "inherit" the completion.

Hmm, well that is in effect what the entrypoint in the dockerfile is attempting to do:

https://github.com/osrf/docker_images/blob/40903f632eca1bf5fef2c8420511b3ddc9c4409b/ros2/source/source/Dockerfile#L101-L102

https://github.com/osrf/docker_images/blob/40903f632eca1bf5fef2c8420511b3ddc9c4409b/ros2/source/source/ros2_source_entrypoint.sh#L5-L6

My old personal hack was to modify the bashrc:

https://github.com/keymint/keymint_tools/blob/9b8d6e2e45a2443b49fa024de2d7e53769bb8749/.docker/keymint_tools/Dockerfile#L22-L23

But this is poor form for a multitude of reasons [mentioned before](https://github.com/osrf/docker_images/pull/113#issuecomment-360917931).

**Comment by ruffsl** [comment]
Here is an easy workaround that can be done by updating the entrypoint:

``` bash
#!/bin/bash
set -e

# setup ros2 environment
source "/opt/ros/$ROS2_DISTRO/setup.bash"
echo 'source "/opt/ros/$ROS2_DISTRO/setup.bash"' >> ~/.bashrc
exec "$@"
```

Because the appending to the bashrc is done at the start of the entrypoint, it doesn't matter what local user the run command is passed at runtime. Not sure if this is would be appropriate for the official use, could be easily incorporated by end users who want to use containers more interactive.
