### ISSUE TITLE
Base Image for Gazebo 9

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#116]
From [Gazebo website](http://gazebosim.org/), gazebo v9 is supported until 2023, I assume in sync for [Ubuntu EOL ](https://wiki.ubuntu.com/Releases) of 18.04. However, as Bionic is yet to be released, and as v9 currently targets 16.04 and 17.10, the question is how we should proceed currently. 

My suggestion would be be that we would target 16.04 for now, with added tags with a `-xenial` postfix, then switch to bionic for the basic tags to 18.04 when supported, while preserving the `-xenial` tags until 16.04's EOL. Basically what we already do with ROS, but now ported for gazebo.

**Comment by j-rivero** [comment]
Thanks @ruffsl, sounds good to me. Let me know if you need me to proceed with any code change.
