### ISSUE TITLE
Handling of EOL Gazebo distros

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#118]
This is analog to #79 but for gazebo.

Several images in this repo are for EOL Gazebo distributions.
As it stands every time ubuntu releases a new image we rebuild all of the Gazebo images.

There are 2 approaches here:
1) As long as a given ubuntu distribution is not EOL we should build up to date images for these platforms regardless of the state of the gazebo distribution (active / EOL)
  - pros: people get the latest security updates from ubuntu
  - cons:
    - we are shipping images in an untested state that doesnt reflect the state of the last supported configuration of that gazebo version
   - use resources to rebuild these (both our CI and the docker infrastructure)

2) As soon as a Gazebo distribution is EOL, we stop building new images for it
(pro / cons: opposite of option 1)

For ROS we decided to go for 1 as this matches the configuration when we stop building debian packages for a given distro. The same logic may or may not apply to gazebo.

/cc @ruffsl @j-rivero @nkoenig

**Comment by ruffsl** [comment]
I like 1, as from a user's perspective, I'd expect a package released into a distro would at least work up to the EOL for that same distro. However, perhaps such ideals are not always practical, given gazebo EOL is usually set months before Ubuntu's EOL for the targeted LTS.

**Comment by mikaelarguedas** [comment]
> However, perhaps such ideals are not always practical, given gazebo EOL is usually set months before Ubuntu's EOL for the targeted LTS.

Yeah as new versions of the package will not be released after it's EOL, I wouldn't expect anything to happen in case it breaks before the EOL of the platform, so I would be in favor of 2 (like for ROS).
That is actually what we will end up doing for Lunar: Lunar will EOL in may 2019 and we will stop building any ROS debs or docker images for it at that point, even though Ubuntu Xenial will not EOL before 2021.

@nkoenig @j-rivero Any comment on this ?

As Gazebo 4, 5 and 6 have been EOL for some time, I am considering doing like we do for ROS and stop building new images for them (aka removing them from the dockerlibrary as well as from CI of this repo).

**Comment by mikaelarguedas** [comment]
Thanks everyone for the feedback (here and offline).
I believed we reached consensus and implemented the option "Stop building images for EOL versions of our projects (ROS and Gazebo) regardless of the EOL status of the base images" so I'm going to close this.
