### ISSUE TITLE
ROS Melodic?

### ISSUE THREAD

**Issue by davetcoleman** [osrf/docker_images#134]
When can we expect to see a Melodic docker added to this repo? Thanks!

**Comment by mikaelarguedas** [comment]
Im planning on building the Melodic docker images as soon as `metapackages` is released (currently blocked by a [few other unreleased repos](http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=metapackages&s=6&r=1)

**Comment by davetcoleman** [comment]
I had to create my own ros-base Docker image since yours is not ready :-/
https://github.com/ros-planning/moveit/pull/885

**Comment by davetcoleman** [comment]
(copied your lunar one and made it install ros-melodic-roslib only)

**Comment by clalancette** [comment]
@mikaelarguedas Can we close this now that https://github.com/osrf/docker_images/pull/135 is merged?

**Comment by mikaelarguedas** [comment]
I was waiting for the images to be built and propagated. I triggered a rebuild of desktop and desktop full manually yesterday so I think we're good :+1: 
https://hub.docker.com/r/osrf/ros/tags/
