### ISSUE TITLE
Trigger rebuild of latest ROS base images

### ISSUE THREAD

**Issue by redkite** [osrf/docker_images#182]
We are trying to use the latest ROS base images for our CI process, but the images are outdated and builds fail.

Is there any way to trigger a rebuild of these images, or do we just have to wait? It's probably to build the full stack for ourselves then. From what I can see in Travis they seem to have failed due to some network timeout issues lately?

**Comment by mikaelarguedas** [comment]
Thanks @redkite for reporting.
Could you provide more information about what image you are trying to use, how you use it in your CI scripts as well as more details about the build failures you experience?

The base images are in the official dockerhub library and rebuilt when new ubuntu images are released. Ways of ensuring rebuilds when a ROS distribution is synced are discussed at https://github.com/osrf/docker_images/issues/112.

> It's probably to build the full stack for ourselves then.

We recommend running an upgrade (`apt update && apt upgrade -y`) to be sure to get the latest ROS packages released before performing builds on top. There shouldn't be a need to rebuild any released package yourself.

> From what I can see in Travis they seem to have failed due to some network timeout issues lately?

Travis is just used for sanity checking on our side, the state of travis does not reflect the state of the images part of the official Docker library.

HTH,

**Comment by mikaelarguedas** [comment]
Sounds good, thanks for the additional information.

>  I think it's caused by newer packages that rely on version 0.5.2 without upgrading rosconsole itself.

If this is the case, these packages should have their `package.xml` modified to reflect the minimal version they require (example [here](https://github.com/ros/pluginlib/blob/b0299cfe88c0bbe742a859b9f38b364a9bd271fe/package.xml#L26)), this way apt will make sure that the installed version is high enough. If you get a chance to identify which packages these are, please consider submitting a PR for listing the minimal rosconsole version.

> Would be nice to have a mechanism to rebuild the docker images after new deb-packages have been published, but I can see that there probably won't be any other way than solving #112 .

Agreed :+1: hopefully we'll get around implementing it in the future.

As there seem to be a workaround, I'm going to close this issue, feel free to comment here if you still face problems and we can reopen this issue

**Comment by mikaelarguedas** [comment]
As a second datapoint: I pulled the latest `ros:kinetic-ros-base` and checked the `rosconsole` version:
```
# apt-cache show ros-kinetic-rosconsole | grep Version
Version: 1.12.13-0xenial-20180222-205214-0800
```
This seem to be the last released version for kinetic: https://github.com/ros/rosdistro/blob/d9bd4bb03c4a9c6e9dead3c5a3b3efaf8c3f52ea/kinetic/distribution.yaml#L9806

Can you make sure you have the latest docker image ? (`docker pull ros:kinetic-ros-base`)

**Comment by redkite** [comment]
Yes, sorry. My bad, it is indeed `ros-kinetic-rosconsole-bridge`. I added `apt upgrade` to my Dockerfile for now, seems to run fine.
