### ISSUE TITLE
docker pull access denied for osrf

### ISSUE THREAD

**Issue by kirk86** [osrf/docker_images#186]
Hi, thank you for publishing theses images.
I am trying to pull ros2 using docker `docker pull osrf/ros2` but I keep getting the following error message
```
Using default tag: latest
Error response from daemon: manifest for osrf/ros2:latest not found
```
Am I doing something wrong here. How are these images supposed to be used? Is there any other tag other than `latest` that we should use?

Thank you in advance!

**Comment by tfoote** [comment]
That's not a access denied, but a failure to resolve. We don't have a `latest` tag in the repository which is the default alias. 

You should pick from one of the tags listed here: https://hub.docker.com/r/osrf/ros2/tags/ such as `bouncy-full`

I'll leave this open as we should probably pick one to be the default and duplicate it as latest so others don't hit this issue.

**Comment by kirk86** [comment]
@tfoote Thank you so much that clarifies things a lot. If you don't mind me asking a second question when we pull ros2 and get a tty to it does gazebo come preinstalled in that ros2 version or do we have to do separate pull for that?

**Comment by ruffsl** [comment]
> we should probably pick one to be the default and duplicate it as latest so others don't hit this issue.

I'd recommend not setting that expectation, given that we don't do such for the `osrf/ros` (ros1) images. I'd imagine after ros2 crystal is released, we can migrate crystal (and possibly past releases) into the official docker library, and leave just the desktop tags hosted on the `osrf` org. Otherwise, I think the abeguiry in there being both a `osrf/ros2:latest` and a `ros2:latest` might be confusing.

> does gazebo come preinstalled in that ros2 version

@kirk86 , gazebo is installed in ros1 image of `osrf/ros:<distro>-desktop-full` given that meta package includes simulation tools, but no such equivalent exists for ros2. You can however write your own custom dockerfile the builds from the ros2 image and installed gazebo on top, although I'm not sure a ro2 gazebo interface exists unless you'd want to leverage ros1-bridge.

**Comment by mikaelarguedas** [comment]
> I'd recommend not setting that expectation, given that we don't do such for the osrf/ros (ros1) images. I'd imagine after ros2 crystal is released, we can migrate crystal (and possibly past releases) into the official docker library, and leave just the desktop tags hosted on the osrf org. Otherwise, I think the abeguiry in there being both a osrf/ros2:latest and a ros2:latest might be confusing.

:+1: that was my thinking as well. We will create a `latest` tag once we migrate the ros2 images to the docker library.

**Comment by kirk86** [comment]
@ruffsl 
> I'm not sure a ro2 gazebo interface exists unless you'd want to leverage ros1-bridge.

just to clarify, ros2-gazebo interface, is still possible to install ros1-brdige and have those things play nicely with each other? Many thanks!

**Comment by ruffsl** [comment]
@kirk86 , porting `gazebo_ros_pkgs` appears to be an action item on the [ROS2 Roadmap](https://github.com/ros2/ros2/wiki/Roadmap) for Crystal Clemmys. As a workaround, I'd expect using ros1-bridge to link gazebo and ros2 would work in the interim, but I haven't necessarily tried.

**Comment by mikaelarguedas** [comment]
Some users successfully used the `ros1_bridge` to link gazebo and ROS2.
You will need to [build a custom bridge](https://github.com/ros2/ros1_bridge#building-the-bridge-from-source) to include support for `gazebo_msgs`.

The port of `gazebo_ros_pkgs` to ROS 2 is in progress, several plugins are already available. I believe the place tracking progress of the migration is this one : https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-integration

**Comment by ruffsl** [comment]
Closing issue, as original topic of missing `latest` tag will be addressed when migrating ros2 images to the official docker hub library.

**Comment by rubenanapu** [comment]
Hey guys, just to let you know the problem seems to be back.
I'm getting:

> Error response from daemon: manifest for osrf/ros2:ardent-basic not found

If I try the "latest" the error is also there as we can see:

```
sudo docker pull osrf/ros2
Using default tag: latest
Error response from daemon: manifest for osrf/ros2:latest not found
```

Additionally, I can't see any tags on https://hub.docker.com/r/osrf/ros2/tags apart from "nightly", which doesn't seen to be a tag.

**Comment by ruffsl** [comment]
ROS images for ROS2 have been migrated to the officially docker library, please see the previous announcement on discourse:

https://discourse.ros.org/t/announcing-official-docker-images-for-ros2/7381

The tags on osrf/ros2 images where mostly temporary as we prepared for official release, thus the notice on the osrf/ros2 repo: `**Experimental** Docker Images for ROS2 development, as repo location and tags are subject to change `. To avoid hosting stale or vulnerable images, the duplicate tags on osrf/ros2 have been removed, and presently host just the nightly images built using the nightly build flat archives. You can now find the desktop tag for ardent/bouncy/crystal at osrf/ros.
