### ISSUE TITLE
Recent ros:kinetic-ros-base-xenial causes some ROS packages to crash

### ISSUE THREAD

**Issue by Axel13fr** [osrf/docker_images#198]
Hi, 
I have had the following problem about a bit more than a month ago: latest kinetic docker images causes crash at start of at least the following nodes: diagnostic aggregator and static tf  transformer. When I compile them from source using the docker image, problem is solved. It really looks like a binary / lib compatibility problem.

By the way, these packages did not crash in previous versions of the docker image (sorry, do not have the exact history of when it started to happen) and it doesn't crash on my current Ubuntu 16.04.

To reproduce the issue:
```
FROM ros:kinetic-ros-base-xenial

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends libgeographic-dev python-catkin-tools && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends \
											ros-kinetic-diagnostic-aggregator \
											ros-kinetic-diagnostic-updater \ 
											&& rm -rf /var/lib/apt/lists/*
```
Then run the image with 
`docker run -it --entrypoint /bin/bash YOU_IMAGE_NAME`
and after sourcing, try to roslaunch an aggregator node (diagnostic_aggregator / aggregator_node).
Same thing for tf / static_transform_publisher.

Do you have any idea ? I will try to rebuild the whole composition of docker files from scratch without cache.

**Comment by Axel13fr** [comment]
So I managed to solve the issue by updating (docker pull) the ubuntu:xenial used in the ros-core docker.
I then built the ros:kinetic-ros-core-xenial image with no-cache option  and finally build the ros:kinetic-ros-core-base image again with no-cache option. When rebuilding the example I gave above, the problem is not there anymore.

But it is STILL THERE if one just docker pull ros:kinetic-ros-base-xenial. Could you trigger a complete rebuild ?

**Comment by sloretz** [comment]
It looks like there might have been an ABI break in one of `diagnostic_aggregator`'s dependencies. If I understand correctly the docker images are rebuilt only when the base (ubuntu) image changes. Having a way to rebuild these more often is tracked in #112.

A workaround is to upgrade all packages in your dockerfile. 

```Dockerfile
FROM ros:kinetic-ros-base-xenial

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
```

There's a bit more info in #182.

**Comment by ruffsl** [comment]
Given this ABI break wasn't reflected in the semantic versioning of the released package, this is mainly an upstream issue for the package maintainer. So I'm closing this as its not specific to these docker images.

However to mitigate this, I've started https://github.com/osrf/docker_images/pull/204 to help keep the images more in sync with upstream.
