### ISSUE TITLE
make build for gazebo9 failes

### ISSUE THREAD

**Issue by mojovski** [osrf/docker_images#207]
Calling make build for gazebo9 fails.
This is the file I execute:
https://github.com/osrf/docker_images/blob/master/gazebo/9/ubuntu/xenial/Makefile

This is the output:
```
E: Version '9.4.1-1*' for 'gazebo9' was not found
The command '/bin/sh -c apt-get update && apt-get install -q -y     gazebo9=9.4.1-1*     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 100
```

**Comment by ruffsl** [comment]
Resolved with https://github.com/osrf/docker_images/pull/208

**Comment by ruffsl** [comment]
See https://github.com/docker-library/official-images/pull/5096
