### ISSUE TITLE
COPY failed building ROS kinetic

### ISSUE THREAD

**Issue by Patrick-Lascombe** [osrf/docker_images#211]
When trying to build the ROS kinetic image by using the command `sudo docker build kinetic/` (kinetic being the file that contains this docker file https://github.com/osrf/docker_images/blob/49d22242e02e9c541a9e85b657e1785617b6f470/ros/kinetic/ubuntu/xenial/ros-core/Dockerfile. I have an error at the step 11/13 : COPY failed: stat /var/lib/docker/tmp/docker-builder329402128/ros_entrypoint.sh: no such file or directory.

Can someone help me fix this ?

Thanks !

**Comment by tfoote** [comment]
There's a file in the directory next to the Dockerfile by that name that needs to be present. If you need more help please ask for help on https://answers.ros.org or a docker specific forum as your question is not particularly ROS related.
