### ISSUE TITLE
Error when trying to run docker GUI 

### ISSUE THREAD

**Issue by wheemzy1** [osrf/docker_images#212]
I'm on Ubuntu 16.04.

I ran the commands listed on the Ros Docker GUI tutorial page, only substituting the ros-melodic image with the kinetic docker image download. 

#I've used with and without sudo 

docker run -it \
    --user=$USER \
    --env="DISPLAY" \
    --volume="/etc/group:/etc/group:ro" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    osrf/ros:kinetic-desktop-full-xenial \
    rqt

I get the following error either way I run it:

docker: Error response from daemon: linux spec user: unable to find user matthew: no matching entries in passwd file.

I'm not a docker master nor system admin, but I think add myself with my username to the daemon group in my /etc/group file but this does not solve the issue.

I would love to know why I'm getting this error and how to resolve.

Really appreciate the help!

**Comment by ruffsl** [comment]
I think that docker error is from the user set in the user arg from the run command not existing in the set of users defined in the docker image chosen. This is not ros specific. If you want to preserve your user permission level while using docker containers, then things get a bit more involved.

I'd suggest looking at some other examples how folks approach this and going back to the docker run docs and reading through all the relevelt argument sections:

* https://docs.docker.com/engine/reference/run/
* https://github.com/jessfraz/dockerfiles
* https://github.com/ruffsl/hsr_demo/blob/19144f5cce8044071c31a87ff684f64e397f5200/docker_demo/ros-gui-docker.bash#L25
