### ISSUE TITLE
Images not being updated

### ISSUE THREAD

**Issue by ross-desmond** [osrf/docker_images#213]
It looks like [ros2 docker image builds](https://hub.docker.com/r/osrf/ros2/builds?page=1) have stopped in the meantime. I see that ros2-crystal is in pull request at the moment and is not currently building. 
**Is this going to change soon? Can we help?**
**Also will ARMx32 and ARMx64 images be available with crystal?**

**Comment by ross-desmond** [comment]
Closed due to: https://discourse.ros.org/t/official-docker-images-for-ros2-crystal-and-arm32v7/6872/10

**Comment by ruffsl** [comment]
> Is this going to change soon? Can we help?

Most folks are on holidays, but if you have time, please checkout the PRs linked in the discourse thread.

> Also will ARMx32 and ARMx64 images be available with crystal?

Now that crystal is out, we could probably follow up with nuclearsandwich again.
