### ISSUE TITLE
indigo-desktop-full doesn't build from the local indigo-desktop image

### ISSUE THREAD

**Issue by jguiraudet** [osrf/docker_images#22]
A minor issue in ros/indigo/indigo-desktop-full/Dockerfile:

The starting images is **"FROM osrf/ros:indigo-desktop"** instead of **"FROM ros:indigo-desktop"**, which make that the indigo-desktop-full is not build with the newest image.

When rebuilding the image from scratch, the consequence is that osrf/ros:indigo-desktop is pulled from the repository.

**Comment by tfoote** [comment]
There is no desktop in the ros images. ([available tags](https://hub.docker.com/r/library/ros/tags)). It has too many GUI dependencies to be accepted in the official repository.

**Comment by ruffsl** [comment]
The [osrf/ros](https://hub.docker.com/r/osrf/ros/) repo under the osrf docker hub profile is an automated build, and is triggers to rebuild desktop tags when ever the official repo is rebuilt, using the same official Dockerfiles kept here. If you are building the images locally, and you'd like to avoid downloading `FROM` images, make sure you build them in order, using the same tag names (e.g. ros:indigo-ros-core -> ros:indigo-ros-base -> osrf/ros:indigo-desktop -> osrf/ros:indigo-desktop-full)

Side note: only use the tags in the osrf/* that are listed in the read me page, the other duplicates tags same as from the ros/* are old. Not sure how to purge them, think I'll need to use the registry API:
https://github.com/docker/docker/issues/8759

**Comment by jguiraudet** [comment]
Yes, I wase trying to rebuild the images locally. 
Thanks for the information about the ros: tags.
