### ISSUE TITLE
 arm64v8 ubuntu14.04+ros indigo

### ISSUE THREAD

**Issue by gakkiHp** [osrf/docker_images#237]
Hello, I have a problem. I can't find the docker based on arm64v8 ubuntu14.04+ros indigo, can you find it, I didn't see it on dockerhub

**Comment by gakkiHp** [comment]
could anyone give me some tips(Dockerfile) to build one? I try some dockerfiles but it is not suitable

**Comment by sloretz** [comment]
Do you mean the Dockerfiles here?

https://hub.docker.com/_/ros

https://github.com/osrf/docker_images/blob/49d22242e02e9c541a9e85b657e1785617b6f470/ros/indigo/ubuntu/trusty/ros-core/Dockerfile
https://github.com/osrf/docker_images/blob/49d22242e02e9c541a9e85b657e1785617b6f470/ros/indigo/ubuntu/trusty/ros-base/Dockerfile
https://github.com/osrf/docker_images/blob/49d22242e02e9c541a9e85b657e1785617b6f470/ros/indigo/ubuntu/trusty/robot/Dockerfile
https://github.com/osrf/docker_images/blob/49d22242e02e9c541a9e85b657e1785617b6f470/ros/indigo/ubuntu/trusty/perception/Dockerfile

**Comment by mikaelarguedas** [comment]
> I can't find the docker based on arm64v8 ubuntu14.04+ros indigo, can you find it, I didn't see it on dockerhub

ROS Indigo does not target the arm64v8 architecture, only i386, amd64 and armhf (aka arm32v7), this means there are no debs created for that platform (and so cannot reuse the Indigo Dockerfiles provided in this repository).
To create a ROS Indigo image for arm64v8, you will have to (cross-)compile all the ROS Indigo packages you need.

**Comment by gakkiHp** [comment]
Ok, thank you very much. It sounds very complicated. I may try it in my spare time later.

**Comment by mikaelarguedas** [comment]
In case the edit was not seen (as github doesnt send notifications for comment edit):

all ROS distributions starting with ROS Kinetic provide arm64v8 packages and docker images, if it's possible for your project I would recommend using a more recent ROS distribution rather than going through the hassle of building all ROS Indigo for that architecture (especially as ROS Indigo will [go EOL next month](http://wiki.ros.org/Distributions))

**Comment by gakkiHp** [comment]
Thank you very much for your suggestion. Actually, I encountered problems when using some tools. The solution on github is to use a lower version of ros. In order to verify this solution, I try to install indigo. I will try to find other solutions. Thank you again for your suggestion
