### ISSUE TITLE
amd64-->arm64v8

### ISSUE THREAD

**Issue by gakkiHp** [osrf/docker_images#240]
Can the amd64 in platform.yaml be changed into arm64v8?

**Comment by mikaelarguedas** [comment]
This issue does not provide enough context to be addressed.

I'm assuming this is a duplicate from the question at https://github.com/osrf/docker_images/issues/237 so I'm going to close it.

I encourage you to post further questions about ROS on [answers.ros.org](https://answers.ros.org/questions/) and to provide sufficient information for the community to answer as specified in the [ROS support guidelines](http://wiki.ros.org/Support)

Thanks!

**Comment by gakkiHp** [comment]
OK，thanks a lot.
