### ISSUE TITLE
Error response from daemon: manifest for osrf/ros2:latest not found

### ISSUE THREAD

**Issue by nicolashey** [osrf/docker_images#241]
Hi everyone !

I'm using ubuntu 16.04 with docker 18.09.3 and when i want to pull ROS 2 on my computer, I got this problem: 

**root@:~#** docker pull osrf/ros2
Using default tag: latest
Error response from daemon: manifest for osrf/ros2:latest not found

What can I do to resolve this ?

**Comment by sloretz** [comment]
By default docker tries to pull a tag named `latest`. The only tag for https://hub.docker.com/r/osrf/ros2 is `nightly`.

```
docker pull osrf/ros2:nightly
```

However, you might want the latest released version instead

```
docker pull osrf/ros:crystal-desktop
```

**Comment by ruffsl** [comment]
Aside from the desktop tags, there are also Official Library Docker Hub Images for ROS2:

https://discourse.ros.org/t/announcing-official-docker-images-for-ros2/7381

```
docker pull ros:crystal 
```
