### ISSUE TITLE
What license are these Dockerfiles under

### ISSUE THREAD

**Issue by cjds** [osrf/docker_images#257]
I was just curious what the License was for this Dockerfile? Other packages in this Group seem to be licensed as BSD (https://github.com/osrf/rosbridge_suite/blob/develop/LICENSE).

**Comment by moriarty** [comment]
@tfoote & @wjwwood & @jacobperron I have the same question as @cjds 

It's easy to extend these dockerfiles with
```dockerfile
FROM ros:melodic
```
```dockerfile
FROM gazebo:gzserver9
```

For basic cases. But if you want to do something more unique like mixing gazebo version with some other ros version, and enabling specific hardware acceleration while minimizing the size of the final docker image you end up needing to write from scratch.

```dockerfile
FROM ubuntu:bionic
```

From this line:
_You can however use this repo to build and customize your own images to fit your software/hardware configuration._

On the [How to use this image](https://registry.hub.docker.com/_/gazebo/) document on docker hub, I assume these are released under a permissive license


> Devices
> As of Gazebo version 5.0, physics simulation under a headless instances of gzserver works fine. However some application may require image rendering camera views and ray traces for other sensor modalities. For Gazebo, this requires a running X server for rendering and capturing scenes. In addition, graphical hardware acceleration is also needed for reasonable realtime framerates. To this extent, mounting additional graphic devices into the container and linking to a running X server is required. In the interest of maintaining a general purpose and minimalistic image which is not tightly coupled to host system software and hardware, we do not include tags here with these additional requirements and instructions. You can however use this repo to build and customize your own images to fit your software/hardware configuration. The OSRF's Docker Hub organization profile contains a Gazebo repo at osrf/gazebo which is based on this repo but includes additional tags for these advanced use cases.

**Comment by ruffsl** [comment]
See suggested fix here: https://github.com/osrf/docker_images/pull/400
