### ISSUE TITLE
Gazebo v9 build fails for arm32v7

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#258]
It looks like the latest release for Gazebo v9 has not been synced for arm32v7, and is blocking docker librage image builds for that architecture:

https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/gazebo/21/console 

```
E: Version '9.8.0-1*' for 'gazebo9' was not found
```

Is there an upstream regression that is blocking this Gazebo release?

arm32v7 [![Build Status](https://doi-janky.infosiftr.net/buildStatus/icon?job=multiarch/arm32v7/gazebo)](https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/gazebo/)

**Comment by ruffsl** [comment]
@j-rivero , any update? Looks like this is still unresolved.

**Comment by mikaelarguedas** [comment]
Looks like there are now 5 cases with missing packages:
gazebo 9 arm64 (stretch + bionic)
gazebo 9 arm32 (stretch + bionic)
gazebo 10 arm32 (bionic)

Are new gazebo packages still being released for arm ?

**Comment by mikaelarguedas** [comment]
@chapulina do you happen to have any insight on this ?

**Comment by j-rivero** [comment]
> Are new gazebo packages still being released for arm ?

arm64 and arm32 on Ubuntu suffer from a couple of bugs, I've created the public issue for this: https://bitbucket.org/osrf/gazebo/issues/2691/compilation-problems-for-arm32-and-armhf . Patches are more than welcome :)

**Comment by mikaelarguedas** [comment]
Sounds good thanks for the update. I don't think I'll have time to look into this but I'll watch the issue.

In the meantime I suggest to remove the arm images from dockerhub to avoid them trying to build them daily.

**Comment by ruffsl** [comment]
I think we can reopen this later if there's ever enough interest in arm for gazebo.
