### ISSUE TITLE
ros2 images out of date

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#259]
It looks like both `ros2:devel` and `ros2:nightly` are out of date, the former causing builds to fails due to outdated colcon packages, the latter resulting in successful builds because not including [recent API changes](https://github.com/ros2/rclcpp/pull/701).

![Screenshot 2019-04-29 12:01:34](https://user-images.githubusercontent.com/6644208/56889417-94fffb80-6a76-11e9-9642-08df516362ed.png)

@nuclearsandwich Is the cron job for these images still running daily ?

@ruffsl FYI

**Comment by nuclearsandwich** [comment]
> Is the cron job for these images still running daily ?

An IP address change and an `/etc/hosts` entry broke the nightly jobs Friday evening. I never turned the devel job on. I think I was waiting for confirmation that it worked.

**Comment by ruffsl** [comment]
> I think I was waiting for confirmation that it worked.

`devel` should be ready to go.
I've only been waiting on announcing it incase I encountered any lingering issues using the Dockerfile daily.

**Comment by mikaelarguedas** [comment]
Thanks @nuclearsandwich for the explanation.
I triggered a rebuild of the devel image manually in the meantime.

> `devel` should be ready to go.
> I've only been waiting on announcing it incase I encountered any lingering issues using the Dockerfile daily.

Sounds good to me. I think we're good to trigger it daily like `ros2:nightly` and confirm no surprises arise.
I'd differ the announcement until we have a daily build and some CI using it daily, I've been waiting to have at least all of `ros_core` released in dashing to start using it in my CIs.

**Comment by nuclearsandwich** [comment]
I've added a nightly trigger for the devel build as well.
