### ISSUE TITLE
ros2:source fails to build because pytest cant be found

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#270]
Currently the source image fails to build for both crystal and dashing. Despite `python3-pytest` being installed on the system, the module cannot be found by `ament_cmake_pytest` resulting in warnings like:
```
--- stderr: rosidl_adapter
CMake Warning at /opt/ros2_ws/install/ament_cmake_pytest/share/ament_cmake_pytest/cmake/ament_add_pytest_test.cmake:73 (message):
  The Python module 'pytest' was not found, pytests can not be run (e.g.  on
  Ubuntu/Debian install the package 'python3-pytest')
Call Stack (most recent call first):
  CMakeLists.txt:31 (ament_add_pytest_test)
```

Some pytests targets in the ROS stack are not checked for existence before setting properties leading to CMake Errors.

Needs some more investigation to figure out why the module is not found and the list of tests that should check for target existence

**Comment by clalancette** [comment]
This looks to be a generic problem with the source install, as @Karsten1987 ran into the same problem and I reproduced it earlier today.

**Comment by mikaelarguedas** [comment]
Yeah working with @Karsten1987 yesterday we ran into it in multiple places.

Is there an issue tracking it on the ROS2 repositories? I tracked down the issue to the pytest version and can suggest pinning the version for ROS2 users until it is fixed upstream or a better workaround is found

**Comment by clalancette** [comment]
> Is there an issue tracking it on the ROS2 repositories? I tracked down the issue to the pytest version and can suggest pinning the version for ROS2 users until it is fixed upstream or a better workaround is found

Not at the moment.  If you don't mind opening an issue and suggesting a patch, that would be great!  Thanks.

**Comment by mikaelarguedas** [comment]
For reference: this issue is being tracked at https://github.com/ros2/ros2_documentation/issues/271 instead of https://github.com/ros2/ros2/issues/722
