### ISSUE TITLE
rostopic doesnt work for osrf/ros:crystal-ros1-bridge

### ISSUE THREAD

**Issue by TheLaas** [osrf/docker_images#276]
Hello

I'm currently working on bridging messages from a ros1-contianer using the osrf/ros:crystal-ros1-bridge. However when running a container I can't list available topics. The `rostopic` command can't be found. 

```
root@0db5eec70c4d:/usr/src/ros_bridge# rostopic
bash: rostopic: command not found
```
I've also tried to source the ros environment but the issue still remains:
```
root@0db5eec70c4d:/usr/src/ros_bridge# source /opt/ros/melodic/setup.bash
ROS_DISTRO was set to 'crystal' before. Please make sure that the environment does not mix paths from different distributions.
root@0db5eec70c4d:/usr/src/ros_bridge# source /opt/ros/melodic/local_setup.bash
root@0db5eec70c4d:/usr/src/ros_bridge# rostopic
bash: rostopic: command not found
``` 
Do I need to install som additional packages in order to get this to work or what am I doing wrong?

**Comment by mikaelarguedas** [comment]
> Do I need to install som additional packages in order to get this to work

Yes, in order to use `rostopic` you will need to install `ros-melodic-rostopic`

The `ROS_DISTRO-ros1-bridge` images come only with a minimal set of ROS 1 packages necessary to bridge the common messages between ROS1 and ROS2. It does not include all the ROS 1 tools provided by `ros_core` (e.g. rostopic, rosnode, rosservice).

You can get the list of installed ROS 1 packages by running `rospack list`.

---

It could be good to provide some common ROS 1 CLI in the bridge images though. As without them it is difficult to interact with the bridge.
How do you feel about this @nuclearsandwich @ruffsl @sloretz ?

We could either add some arbitrarily, e.g.:
```
ros-melodic-rosnode
ros-melodic-rosservice
ros-melodic-rostopic
ros-melodic-roswtf
```

Or install a metapackage containing them such as `ros_comm`
This would result in the following packages being installed:
```
binfmt-support
libpipeline1
ros-melodic-message-filters
ros-melodic-mk
ros-melodic-ros
ros-melodic-ros-comm
ros-melodic-rosboost-cfg
ros-melodic-roscreate
ros-melodic-roslang
ros-melodic-roslisp
ros-melodic-rosmake
ros-melodic-rosnode
ros-melodic-rosservice
ros-melodic-rostest
ros-melodic-rostopic
ros-melodic-roswtf
sbcl
```

**Comment by sloretz** [comment]
Some people might want a small image to base their images on, and if tools aren't needed then they don't want them included. Others might want want to use the images as a starting point to try a new version of ROS, and including more tools makes the experience better.

If we don't already have a policy on it, how about images in the official library (like `ros:crystal-ros-core`) should super minimal (like `ubuntu:18.04` is very minimal), and images in `osrf/` (like `osrf/ros:crystal-ros1-bridge`) should be super convenient. If that were the policy I would +1 to adding ros-comm.

**Comment by mikaelarguedas** [comment]
> Some people might want a small image to base their images on, and if tools aren't needed then they don't want them included. Others might want want to use the images as a starting point to try a new version of ROS, and including more tools makes the experience better.

:+1:

> how about images in the official library (like ros:crystal-ros-core) should super minimal (like ubuntu:18.04 is very minimal), and images in osrf/ (like osrf/ros:crystal-ros1-bridge) should be super convenient.

Another way to look at it is that there are currently no ROS image not including the basic CLI except the bridge one, e.g.:
- `ros:melodic-ros-core` in ROS 1 includes `ros_comm`
- `ros:crystal-ros-core` in ROS 2 includes all the [ros2cli packages](https://github.com/ros2/variants/blob/ff42b4e2fccfd8ed8bf0438167d99c3e4f9b7f09/ros_core/package.xml#L51-L67).

Following that pattern I'm also inclined to say that the `ros1_bridge` one should include both the ROS 1 and ROS 2 "core" CLI packages as it's meant to be a bigger image for people to experiment with the `ros1_bridge`

**Comment by sloretz** [comment]
> Another way to look at it is that there are currently no ROS image not including the basic CLI except the bridge one, e.g.:

That's enough for me to +1

**Comment by mikaelarguedas** [comment]
@TheLaas This should be addressed by https://github.com/osrf/docker_images/pull/279.

Once the images are rebuilt you should be able to use rostopic out of the box, e.g. :
```
docker run -it --rm osrf/ros:bouncy-ros1-bridge
# source /opt/ros/melodic/setup.bash
# roscore &
# rostopic list
```
