### ISSUE TITLE
Add cron job to keep osrf/ros images fresh 

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#277]
It seems docker hub has blacklisted official library images from being used as `REPOSITORY LINKS`:

https://www.reddit.com/r/docker/comments/awjndk/docker_hub_automatically_rebuild_on_base_image/ei9dxk8/

So now our `osrf/ros`, `osrf/ros2` repo are not staying up to date. We may need a cron job or something to periodically trigger rebuilds whenever the official images update.

**Comment by mikaelarguedas** [comment]
Oh good to know..
The `osrf/ros2` images are already triggered nightly. 
For the `osrf/ros` ones, it may make sense to have something triggering them only when the base image changes rather than on a fixed period.

**Comment by ruffsl** [comment]
> only when the base image changes rather than on a fixed period.

This can occur if we update the manifest, or if Ubuntu/Debian update the base image. We could just check if the sha digest for the official Ros image has changed. We might need to add a meta file to track this state change for the CI to detect. Not sure how we could get more event driven other than poling often. We could also try being efficient by only triggering child image builds for dependent image. I kind of wish docker hub didn't deprecate the trigger behavior for linking official repos, but I can see why they decided to.

**Comment by gavanderhoorn** [comment]
@ruffsl  @mikaelarguedas: is this still something you're looking into? According to Docker Hub, most `desktop` and `desktop-full` images are almost 6 months old.

**Comment by mikaelarguedas** [comment]
This completely fell off my radar... Thanks for the reminder!
I'm manually triggering a rebuild of all desktop images today and will try to find time to implement an automated fix in the coming weeks

**Comment by ruffsl** [comment]
Resolved with https://github.com/osrf/docker_images/pull/588#issuecomment-1042236352
