### ISSUE TITLE
Rebuild only affected dockerfiles

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#280]
I noticed that https://github.com/osrf/docker_images/pull/279 triggered a rebuild of all the images (`ros` and `ros2` ones).

It would be great to find a way to restrict the build to only the modified `Dockerfile`s.
Based on https://github.com/docker/hub-feedback/issues/403 there doesn't seem to be a good way to do it at the moment, I was hoping that playing with the build context would allow us to restrict which images are being built.

I'm opening this in case anyone has insights of which direction could be explored to improve this.

**Comment by JJ** [comment]
Check out my comment there. Basically, adding a `post_checkout` hook that checks for Dockerfiles in the last commit (there's no better way, apparently)

**Comment by mikaelarguedas** [comment]
Since then we moved most of our images to the official library of docker. The other images are built and pushed via github actions and we implemented the logic to check / build / push only when necessary so I'm going to close this.

Thanks to @JJ for the tip though!
