### ISSUE TITLE
Ubuntu Trusty is EOL

### ISSUE THREAD

**Issue by tianon** [osrf/docker_images#282]
See https://github.com/docker-library/official-images/pull/6103 -- the following affected tags should be either replaced or removed:

```console
$ bashbrew from ros | grep trusty
ros:indigo-ros-core: ubuntu:trusty
ros:indigo-ros-core-trusty: ubuntu:trusty
ros:indigo-ros-base: ros:indigo-ros-core-trusty
ros:indigo-ros-base-trusty: ros:indigo-ros-core-trusty
ros:indigo: ros:indigo-ros-core-trusty
ros:indigo-robot: ros:indigo-ros-base-trusty
ros:indigo-robot-trusty: ros:indigo-ros-base-trusty
ros:indigo-perception: ros:indigo-ros-base-trusty
ros:indigo-perception-trusty: ros:indigo-ros-base-trusty
```

Just as a reminder (and to be explicitly clear), removing tags from the `library/ros` file will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by mikaelarguedas** [comment]
Thanks @tianon for pointing it out !

Indigo images here need to point to the snapshots/EOL ros apt repo and be rebuilt one last time being retired.

**Comment by mikaelarguedas** [comment]
@nuclearsandwich Do you know if there is a timeline for the trusty/indigo packages to be pushed as `final` to the snapshot repository ?
(Similar question regarding lunar and ardent packages)

**Comment by ruffsl** [comment]
> Indigo images here need to point to the snapshots/EOL ros apt repo and be rebuilt one last time being retired.

Oh, I guess answers https://github.com/osrf/docker_images/issues/288

**Comment by tfoote** [comment]
The final snapshots are now available for Trusty platforms.

**Comment by mikaelarguedas** [comment]
PR updating the EOL images to the snapshots repo at https://github.com/docker-library/official-images/pull/6401

Once they are rebuilt the tags will be removed
