### ISSUE TITLE
Difference between these images and the ROS Docker Official Images is unclear

### ISSUE THREAD

**Issue by NoahAndrews** [osrf/docker_images#283]
My understanding is that most users (especially of ROS2) will want to use the Docker Official Images located at https://hub.docker.com/_/ros, so shouldn't the README (and by extension the [`osrf/ros2` Docker Hub page](https://hub.docker.com/r/osrf/ros2/)) link to that page? I almost went through the trouble of maintaining my own ROS2 dockerfile, because the one here doesn't support ARM, and I didn't realize that the Docker Official images had builds for ROS2.

**Comment by mikaelarguedas** [comment]
Thanks @NoahAndrews for pointing out that the Readme was outdated.

See https://github.com/osrf/docker_images/pull/285 for a minimal change trying to clarify things

**Comment by NoahAndrews** [comment]
👍

**Comment by mikaelarguedas** [comment]
@NoahAndrews can you please check if https://github.com/osrf/docker_images/pull/305 addresses this issue?

**Comment by NoahAndrews** [comment]
That's perfect!

**Comment by NoahAndrews** [comment]
Thanks @ruffsl
