### ISSUE TITLE
[question] When should the `ros:latest` tag start pointing to ros2 ?

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#286]
While I remember it being discussed, I couldn't find past discussions about this.

Except this [discourse post](https://discourse.ros.org/t/announcing-official-docker-images-for-ros2/7381/1) mentioning it:

> The `latest` tag was left to remain pointing to the latest ROS1 LTS available (currently melodic), presumably until a LTS distro for ROS2 is released.

Now that Dashing is out it seems like a good time to restart this discussion.
Should the `ros:latest` tag start pointing to Dashing ? or is it something best suited for a future ROS 2 LTS distribution (e.g. targeting 20.04) once the last official distro of ROS 1 is out ?

Tagging @nuclearsandwich @sloretz @tfoote @ruffsl  for feedback.

**Comment by ruffsl** [comment]
This was originally discussed on a respective docker-library/docs PR to refactor for ROS2:

https://github.com/docker-library/docs/pull/1381#pullrequestreview-185320039 

> Now that Dashing is out it seems like a good time to restart this discussion.
> Should the ros:latest tag start pointing to Dashing ?

I think we start with dashing given its LTS status. Aside from updating the docs on docker-library/docs, I'd suggest we retire the old docker-library README/examples that where ROS1 centric to something like articles in http://wiki.ros.org/docker .

**Comment by ruffsl** [comment]
BTW @mikaelarguedas , let me know if you have any feedback on docker-library/docs#1381 .

**Comment by nuclearsandwich** [comment]
My intuition tells me that someone looking for the "latest ROS" would be expecting Melodic. I think our docs should be pushing people to use a label for a specific rosdistro and in those docs we can suggest the current ROS 2 release (or LTS) or ROS 1 LTS as the most common options.

**Comment by ruffsl** [comment]
There already seems to be confused about the existence of ROS2 on DockerHub: https://github.com/osrf/docker_images/issues/283

So I think we should be pushing ROS2 LTS as latest, and link back to old wiki for those still expecting ROS1. The length of the registry readme is hard capped, and there isn't room for presenting both in meanful detail.

**Comment by mikaelarguedas** [comment]
@sloretz @tfoote @nuclearsandwich do you have any feedback on this ?
It would be useful so that the docs PR can be merged or updated accordingly

**Comment by tfoote** [comment]
I would suggest that we consider using Focal as the crossover point? Noetic and Focal will come out and as both LTSs. That's a good point for people to have to choose which one they want. And Noetic can be thought of as final not latest.

**Comment by mikaelarguedas** [comment]
As of ROS 2 Foxy, the `ros:latest` tag points to `ros:foxy-ros-base-focal`
