### ISSUE TITLE
Gazebo GUI from docker

### ISSUE THREAD

**Issue by nicoamaro** [osrf/docker_images#289]
Hi there, I have some troubles running gazebo in debian so I try to run it from docker. I spent some time to make it work and I think it could be included in the readme of dockerhub webpage

```docker run -ti --rm        -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix gazebo /usr/bin/gazebo xhost local:```

some volumes are missing of course and it could be improve but it could be usefull anyway.

**Comment by sloretz** [comment]
Hi @nicoamaro, you might be interested in [rocker](https://github.com/osrf/rocker). It's a tool for running docker images, and it can make it easier to launch GUI's from docker containers.

```
rocker --nvidia osrf/ros:melodic-desktop-full gazebo
```

**Comment by ruffsl** [comment]
As @sloretz pointed out, rocker is a great choice. Documentation for using GUIs with Docker and ROS/Gazebo also exists on the ROS wiki here: http://wiki.ros.org/docker/Tutorials/GUI
