### ISSUE TITLE
Adding a source tag to ROS2 automated repo

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#294]
Currently, the `osrf/ros2` automated dockerhub repo is triggered by a daily cron job to rebuild `osrf/ros2:nightly` and `osrf/ros2:devel`. I've been wondering if it would make sense to include `osrf/ros2:source` in the daily updated tags.

One possible use case could be caching source workspace builds used for downstream packaging, like catching undeclared dependencies by building within a single consolidated workspace:

https://github.com/ros-planning/navigation2/issues/496

Thoughts?

**Comment by mikaelarguedas** [comment]
Do you still have a need for this?

I had this as part of https://github.com/osrf/docker_images/pull/348, it seems to build successfully though slowly (~1:30hr without any kind of caching).


I'm curious of your thoughts after experimenting with a big source image for a while:
> like catching undeclared dependencies by building within a single consolidated workspace

Would there be a way to do this with the current nightly image? 
Or using the nightly ci jobs artifacts? (e.g. http://build.ros2.org/view/Eci/job/Eci__nightly-extra-rmw-release_ubuntu_bionic_amd64)

How would one go to provide information to consumers of the image?
It seems like the consumers would need to build in the exact same conditions as the parent image, is that right? (same install layout, same build type, build flags etc)

**Comment by ruffsl** [comment]
As we talked offline, perhaps another use for this could be to just keep a watch on the source Dockerfile to check that it still works and is up-to-date with the necessary build requirements.

But for use in downstream testing, perhaps there might be a more thorough approach where like the build farm; we could use some boiler plate to build and step through the workspace, installing dependencies as needed while traversing the dependency graph. However, I suppose not even that would root out missing dependencies for parallel forks in the dependency graph if only a single system environment is used. Like you mentioned, @mikaelarguedas , perhaps there would be a better way to leverage the archive from the buildfarm, as it largely does this already for the core .repo packages.

**Comment by ruffsl** [comment]
We can re-open this later if there's ever renewed interest in the idea.
