### ISSUE TITLE
Boost libraries missing when building ROS2 Dockerfile

### ISSUE THREAD

**Issue by BioMechanico** [osrf/docker_images#30]
When I build this Dockerfile it complains about missing Boost libraries. Am I missing something obvious? 

```
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_thread
          boost_system
          boost_date_time
          boost_chrono
          boost_regex
          boost_atomic

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  cmake/dev/boost_libraries.cmake:19 (find_package)
  CMakeLists.txt:147 (check_boost)


CMake Error at cmake/dev/boost_libraries.cmake:21 (message):
  Cannot find Boost components: thread;system;date_time;chrono;regex;atomic
Call Stack (most recent call first):
  CMakeLists.txt:147 (check_boost)
```

**Comment by scpeters** [comment]
which docker file are you building?

**Comment by BioMechanico** [comment]
I'm sorry, it's the ros2 Dockerfile.  If I insert some apt-get commands for boost at the very beginning:
```

...
MAINTAINER Nate Koenig nkoenig@osrfoundation.org

RUN apt-get update -y
RUN apt-get install -q -y \
    build-essential \
    libboost-dev \
    libboost-thread-dev \
    libboost-date-time-dev \
    libboost-atomic-dev \
    libboost-chrono-dev \
    libboost-system-dev \
    libboost-regex-dev

# ROS1 Repo Setup ##############################################################
...
```

Then it works

**Comment by ruffsl** [comment]
This dockerfile hasn't been touch in a while, so I could see why something might have changed, looks like 'build-essential' it alread in the tempalte though:
https://github.com/osrf/docker_images/blob/master/ros2/images.yaml.em

However, I thought ros2 was going to be free of boost dependencies, to help slim things down for embedded targets, am I mistaken or has this changed?

**Comment by tfoote** [comment]
We're not using boost in the core, but FastRTPS uses boost in it's implementation. We will need to add these dependencies as added here: https://github.com/ros2/ros2/wiki/Linux-Development-Setup

**Comment by BioMechanico** [comment]
Those instructions appear quite recent. I think I'll try to make a Dockerfile from them. Thanks you guys for responding so quickly

**Comment by ruffsl** [comment]
If you could send back a PR with the minimum changes to the template and dockerfile, we could review it a update the files here. I have a PR https://github.com/osrf/docker_images/pull/26 I've been meaning to check that has a Dockerfile to generate the Dockerfiles from the templates you could use.

**Comment by rohbotics** [comment]
PR #37 fixes this, the dockerhub builds work now

**Comment by ruffsl** [comment]
Thanks @rohbotics
