### ISSUE TITLE
How to set Python 3 as the `ROS_PYTHON_VERSION` for Melodic image

### ISSUE THREAD

**Issue by akouri-doordash** [osrf/docker_images#309]
It appears that the docker file for ros melodic on Ubuntu defaults to using Python 2. When I set the `ROS_PYTHON_VERSION` later on in my own docker file which inherits from this one, the `ROS_PYTHON_VERSION` variable gets overwritten by `source devel/setup.bash`.

Am I thinking about this wrong, or do we need to create another Dockerfile for those wishing to use Python 3?

**Comment by sloretz** [comment]
Melodic needs to be built from source to in order to use python 3.

There's some work being done on instructions for building melodic with python 3 (it's not supported, but it's handy for finding Python 3 issues), but they're not out yet. Those could be put into a Dockerfile.

**Comment by tfoote** [comment]
I'm going to close this as I don't think there there's anything to be tracked for change here.
