### ISSUE TITLE
Latest ROS2 nightly docker not starting

### ISSUE THREAD

**Issue by pbaughman** [osrf/docker_images#331]
Hi, sorry if this is the wrong place for this, but I'm having trouble starting the latest ros2:nightly docker image

```
pete.baughman@pete-baughman:$ docker run --rm -it osrf/ros2:nightly
Traceback (most recent call last):
  File "/opt/ros/eloquent/_local_setup_util.py", line 322, in <module>
    main()
  File "/opt/ros/eloquent/_local_setup_util.py", line 66, in main
    args.additional_extension
  File "/opt/ros/eloquent/_local_setup_util.py", line 185, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 244, in process_dsv_file
    additional_extension=additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 244, in process_dsv_file
    additional_extension=additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 219, in process_dsv_file
    type_, remainder, prefix)
  File "/opt/ros/eloquent/_local_setup_util.py", line 291, in handle_dsv_types_except_source
    assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set-if-unset
```

Yesterday's runs just fine:

```
pete.baughman@pete-baughman:$ docker run --rm -it f9dc4eb20eed
[connext_cmake_module] Warning: The location at which Connext was found when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory, and the NDDSHOME e
nvironment variable has not been set. Support for Connext will not be available.
root@207a0c4fc550:/# 
```

It's got something to do with trying to source /opt/ros/eloquent/setup.bash

**Comment by dirk-thomas** [comment]
You will need at least `colcon-core` 0.4.3 to build the current master of ROS 2.

**Comment by mikaelarguedas** [comment]
thanks for reporting, this is the right spot for reporting.

> You will need at least colcon-core 0.4.3 to build the current master of ROS 2 (and be able to source the setup file afterwards).

The image already has 0.4.3

Looks like ament [changed it's generated files](https://github.com/ament/ament_package/pull/102) and [colcon](https://github.com/colcon/colcon-core/pull/250) as well but the colcon change was released and not the ament one. So the assumption that the setup file from `ros-eloquent-ros-workspace` allows you to source the nightly workspace doesn't hold.

@dirk-thomas is there an ETA for the release of the ament_package change ?

**Comment by dirk-thomas** [comment]
> is there an ETA for the release of the ament_package change ?

Today.

**Comment by sloretz** [comment]
FYI `ament_package` `0.8.4` https://github.com/ros/rosdistro/pull/22741

**Comment by mkhansen-intel** [comment]
I'm seeing the same issue. I'm assuming tonight's nightly build should pick up the ament_package change and we should be OK tomorrow?

**Comment by zmk5** [comment]
@mkhansen-intel I am curious too. I will check tomorrow and update the issue if everyone would like.

**Comment by pbaughman** [comment]
I'm seeing the same problem with today's image:

```
pete.baughman@pete-baughman:~/$ docker images
REPOSITORY                                                TAG                     IMAGE ID            CREATED             SIZE
osrf/ros2                                                 nightly                 cccd8da348a9        15 hours ago        3.93GB
. . .
pete.baughman@pete-baughman:~/$ docker run --rm -it osrf/ros2:nightly
Traceback (most recent call last):
  File "/opt/ros/eloquent/_local_setup_util.py", line 322, in <module>
    main()
  File "/opt/ros/eloquent/_local_setup_util.py", line 66, in main
    args.additional_extension
  File "/opt/ros/eloquent/_local_setup_util.py", line 185, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 244, in process_dsv_file
    additional_extension=additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 244, in process_dsv_file
    additional_extension=additional_extension)
  File "/opt/ros/eloquent/_local_setup_util.py", line 219, in process_dsv_file
    type_, remainder, prefix)
  File "/opt/ros/eloquent/_local_setup_util.py", line 291, in handle_dsv_types_except_source
    assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set-if-unset
```

**Comment by dirk-thomas** [comment]
> The image is currently still broken because the package didn't make it to the testing repo yet.

The sync to from `building` to `testing` happens automatically if (and only if) a threshold of packages has been rebuild successfully. That was only the case early this morning (see http://build.ros2.org/job/Erel_sync-packages-to-testing_bionic_amd64/108/) so your nightly build might have happened earlier.

**Comment by mikaelarguedas** [comment]
Correct, but in this case the missing part is that the job you linked to was supposed to trigger `upload_testing` for the package to be synced to `packages.ros.org` and was not configured to do so

**Comment by dirk-thomas** [comment]
Good point, the reason the `upload_testing` job wasn't triggered yet is because some of the other platforms (`v8` and `hf`) have not reached the threshold yet.

**Comment by mkhansen-intel** [comment]
It looks like the `nightly` was built before the changes, can someone re-trigger a build for it? If so I'll test it today.

BTW - the `devel` build seems fine, it was built more recently. I am able to run it. I don't know what's different about the two but you could possibly just re-tag it to nightly for today if that's easier?

**Comment by mkhansen-intel** [comment]
This is blocking our CI, can a re-trigger be done? We'd really appreciate it!

**Comment by ruffsl** [comment]
Docker Hub is slow (~1hr build), so I've just manually pushed tags from master. Please check now.

**Comment by pbaughman** [comment]
@ruffsl It is working for me with image 5adc8da51cae:

```
pete.baughman@pete-baughman:~$ docker images | head -n 2
REPOSITORY                                                TAG                     IMAGE ID            CREATED             SIZE
osrf/ros2                                                 nightly                 5adc8da51cae        5 hours ago         3.93GB

pete.baughman@pete-baughman:~$ docker run --rm -it osrf/ros2:nightly
[connext_cmake_module] Warning: The location at which Connext was found when the workspace was built [[/opt/rti.com/rti_connext_dds-5.3.1]] does not point to a valid directory, and the NDDSHOME e
nvironment variable has not been set. Support for Connext will not be available.
root@7f89736b5c05:/# 

```

**Comment by mikaelarguedas** [comment]
Looks like navigation2 and other repos using it for nightly CI are back to happiness using the automatically built image.

Thanks for reporting and testing !

**Comment by mkhansen-intel** [comment]
Thanks for fixing this!
