### ISSUE TITLE
Why is there no image for gazebo:gzweb10?

### ISSUE THREAD

**Issue by jonaspetersorensen** [osrf/docker_images#333]
I can see the targets have been commented out in https://github.com/osrf/docker_images/blob/00d02282c2393ccde655fa0c333b4410a10b3985/gazebo/10/ubuntu/bionic/Makefile
```
# @docker build --tag=gazebo:gzweb10-bionic			gzweb10/.
```

Just curious to why not build it and make it available in docker hub?

**Comment by jonaspetersorensen** [comment]
Doh, I see why, the build fails :P

There are at least 2 problems here:
- The install of nodejs and related software will fail
- (When nodejs is installed correctly) The build of gzweb will fail

**Comment by jonaspetersorensen** [comment]
I got it to build and run by changing how `nodejs` and related software is installed.
`npm` has been diststributed with `nodejs` for some time now, so removing the separate installation for that.
`gzweb` build will fail with latest `nodejs` versions, so I bumped back the version until I got one that worked.

[Source file](https://raw.githubusercontent.com/osrf/docker_images/00d02282c2393ccde655fa0c333b4410a10b3985/gazebo/10/ubuntu/bionic/gzweb10/Dockerfile)

Changes
```
# install packages
RUN apt-get update && apt-get upgrade -y && apt-get install -q -y \
    build-essential \
    cmake \
    imagemagick \
    libboost-all-dev \
    libgts-dev \
    libjansson-dev \
    libtinyxml-dev \
    mercurial \
    pkg-config \
    psmisc \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# install gazebo packages
RUN apt-get update && apt-get install -q -y \
    curl \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -q -y nodejs nodejs-legacy \
    libgazebo10-dev=10.1.0-1* \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by ruffsl** [comment]
Perhaps you could open a PR with your fix and ping @scpeters or @chapulina

**Comment by jonaspetersorensen** [comment]
Most likely there will have to be a change to the dockerfile template used to generate the gwiz dockerfile. My best guess is that it is this file?
https://github.com/osrf/docker_templates/blob/master/docker_templates/templates/docker_images/create_gzweb_image.Dockerfile.em

**Comment by ruffsl** [comment]
Yeah, having the special case for npm versioning in the template install logic might be tricky. Shame we can't just build it using the version of npm that ships with the distro list gazebo targets. Could gzweb itself be updated to use the current version, then we just modify then template to checkout a Target version of gzweb?

**Comment by jonaspetersorensen** [comment]
That would be the best option. That said, from my "late to the party/outsider" perspective I think it would require quite some work as the gzweb code is quite old, and the the web world move on so very very quickly.

**Comment by ruffsl** [comment]
> it would require quite some work as the gzweb code is quite old, and the web world move on so very quickly.

Could you open a ticket with the gzweb repo about what you mean? I could remind some of the gazebo devs about it when seeing them at ROSCon, but I wouldn't be able to explain what would need to be improved myself.

**Comment by ruffsl** [comment]
Closing from inactivity, but PRs to fix gzweb build are welcome.
