### ISSUE TITLE
docker images do not contain rosserial_client and rosserial_python

### ISSUE THREAD

**Issue by altineller** [osrf/docker_images#340]
Previously someone asked: https://github.com/osrf/docker_images/issues/189 

This error happens because the docker images do not contain rosserial packages.

How can we add rosserial packages to robot image?

Best regards,
Can

**Comment by ruffsl** [comment]
You could delivered a child image that builds from the robot tag image, that simply apt installs the rosserial package. The tags provided here are simply based upon the meta packages available in ros. If you think the meta packages should be modified, then you'd likely need to open a PR for the relevant REP.

**Comment by mikaelarguedas** [comment]
This answer is similar to the previous one providing extra links to the mentioned resources.

As pointed out in previous issue linked in description and previous comment: the docker images reflect the content of the respective [ROS metapackages](https://github.com/ros/metapackages), so e.g. the `desktop` image will contain exactly the same packages as if you install the `ros-ROS_DISTRO-desktop` deb package.

What is included in these packages is defined by a REP. For example for ROS Melodic and newer, [REP150](https://github.com/ros-infrastructure/rep/blob/master/rep-0150.rst) is used
The REP can be modified via Pull Request, but a strong rationale should be provided to explain why the packages are essential to all users of these packages.

The alternative recommended by @ruffsl seems the quickest / most likely way forward for your use case:
Create a dockerfile based on the `robot` image and install the packages you need on top of it.

**Comment by altineller** [comment]
Thank you for the explanation.

I managed to get my own images rolling.
