### ISSUE TITLE
Gazebo on kinetic-desktop-full-xenial throws error "no namespace" on first startup

### ISSUE THREAD

**Issue by FirefoxMetzger** [osrf/docker_images#352]
I'm not 100% on which repo would be most appropriate to raise this issue, so I'm happy to migrate if this isn't the correct place. 

I'm experiencing problems launching gazebo from a docker container. The first time I start it, gazebo throws the error `No namespace found`. Presumably because it can't connect to the model database? The second time I start it everything works smoothly. I'm happy to provide a PR if somebody points me in the right direction regarding a fix :) I don't know the code base, so I'm not sure where to start. 

The wider context of this issue is that I am simulating the Franka Emika Panda robot in Gazebo, an due to this problem the ROS controller is crashing and hence the pipeline fails. When I keep the container running and simply restart ROS it is working like a charm.

# MWE
1) allow sharing of the local display server with docker: `xhost +local:root` Note that this method is a potential security problem, and there are safer ways. It is, however, the fastest way for a quick test like this.
2) start a fresh kinetic instance: 
```bash
docker run -it --env="DISPLAY" --env="QT_X11_NO_MITSHM=1"  --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" osrf/ros:kinetic-desktop-full-xenial bash
```
3) Launch Gazebo in verbose mode: `gazebo --verbose`

Expected behavior: Gazebo launches smoothly.
Actual behavior: See [gazebo.log](https://github.com/osrf/docker_images/files/4076255/gazebo.log)

Interestingly, this problem disappears the second time I try to launch gazebo in the same container. My guess is that there are some cache that isn't populated on first startup and causes the fault?

**Comment by FirefoxMetzger** [comment]
Update: Upon further inspection, this seems to be caused by Gazebo loading the `empty.world` on startup, for which it (of course) doesn't have the models `sun` and `ground plane`. It tries to download these models from the model database and seems to struggle reaching it. Adding the two models solves this problem.

I can fix this locally by including the two models in the image I build from the osrf image, but I think it could be better to fix the problem upstream. Suggestions?

**Comment by mikaelarguedas** [comment]
This looks like a gazebo7 packaging issue as the problem does not happen with gazebo9.
<details>

ROS kinetic / gazebo 7.0.0
```
root@55229bb67619:/# dpkg -L gazebo7-common | grep sun
```

Gazebo 7.16.0
```
root@36365b182db1:/# dpkg -L gazebo7-common | grep sun
/usr/share/gazebo-7/models/sun
/usr/share/gazebo-7/models/sun/model.config
/usr/share/gazebo-7/models/sun/model.sdf
```

</details>

I would not fix it in the docker images as it would be more of a hack than a proper fix and not apply generally to all images.

I suggest you install a more recent version of Gazebo7 (from packages.osrfoundation.org) that ships with the models.

@j-rivero FYI

**Comment by ruffsl** [comment]
> I can fix this locally by including the two models in the image I build from the osrf image, but I think it could be better to fix the problem upstream. Suggestions?

For everyday use, I'd suggest you mount models into the container user a volume at runtime, rather than baking them into the docker image, e.g. `--volume /home/foo/.gazebo:/root/.gazebo`. This of course is a choice based on your deployment requirements. Perhaps it may be more convenient distributing model files in the image, but I'm not sure they should be baked in the official images, if gazebo does not include them at installation.

**Comment by FirefoxMetzger** [comment]
> For everyday use, I'd suggest you mount models into the container user a volume at runtime, rather than baking them into the docker image, e.g. --volume /home/foo/.gazebo:/root/.gazebo.

A good suggestion! Unfortunately, it isn't better then baking the models into Gazebo in my case, as the image is shared between multiple workstations on different networks, and doesn't download any other models than `sun` and `ground_plane`, which aren't that large.

> but I'm not sure they should be baked in the official images, if gazebo does not include them at installation.

Gazebo doesn't need to distribute models, because they can assume a persistent model cache at `$GAZEBO_MODEL_PATH`; an assumption the docker version can't make. While it's okay to take time to download what is needed in the bare bones setting, it significantly increases startup time of the container. So I think it's more of a trade-off between container startup time and image size.

In my case the increased startup time leads to a very strange interaction (which frankly I haven't fully understood yet). It seems that `ros_control` tries to start controllers for the robot joints and doesn't find anything to control, because gazebo is still downloading models and loading `empty.world`. This then causes the controllers to stop, and sequentially MoveIt to not find the controllers. The end result being a broken pipeline.

> I suggest you install a more recent version of Gazebo7 (from packages.osrfoundation.org) that ships with the models.

This sounds promising; I will check that out once I get back into the lab on Monday. Would it make sense to update the gazebo version used by ros:kinetic to 7.16 in this case?

**Comment by ruffsl** [comment]
> While it's okay to take time to download what is needed in the bare bones setting, it significantly increases startup time of the container. So I think it's more of a trade-off between container startup time and image size.

This is where creating your own child image that builds from the parent image make more sense:

``` Dockerfile
FROM osrf/ros:kinetic-desktop-full-xenial
RUN <wget/curl gazebo model files here>
CMD bash
```

```
$ docker build -t firefoxmetzger/ros:kinetic-custom-xenial .
$ docker push firefoxmetzger/ros:kinetic-custom-xenial
...
$ docker pull firefoxmetzger/ros:kinetic-custom-xenial
```

**Comment by FirefoxMetzger** [comment]
Your suggestion is the solution I was using so far.

I also just tried upgrading to gazebo 7.16 as the first layer of my Dockerfile
```
RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list' \
    && curl http://packages.osrfoundation.org/gazebo.key | apt-key add - \
    && apt-get update \
    && apt-get upgrade -y gazebo7 libgazebo7-dev \
    && rm -rf /var/lib/apt/lists/*
```
This also solves the problem :) and I feel the solution is cleaner than embedding model files into the repository, so that's the one I'll be going with. 

As there doesn't seem to be any change to the base images as a result of our discussion, should we close this issue?

**Comment by mikaelarguedas** [comment]
> This also solves the problem :) and I feel the solution is cleaner than embedding model files into the repository, so that's the one I'll be going with.

:tada: 

> As there doesn't seem to be any change to the base images as a result of our discussion, should we close this issue?

Right, the base images won't be modified to stick to the content and version of the packages from the official installation instructions.

Closing
