### ISSUE TITLE
Provide automated builds for gzclient ?

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#353]
Currently there are no images being built at https://hub.docker.com/r/osrf/gazebo/

Providing the gzclient images would be useful (e.g. in cases like https://github.com/osrf/docker_images/issues/352)

@ruffsl @j-rivero  do you remember why these were never configured to start with ?

**Comment by ruffsl** [comment]
Just as `osrf/ros` hosts the desktop meta packages given we didn't want to rope in all the X11 stuff into the offical `library/ros` images, I had sort of planed for `osrf/gazebo` to host the GUI related tags for gzclient and gzweb, but I think the gazebo team never got around to splitting the gazebo apt package into gzserver and gzclient packages, so `library/gazebo` i think already includes gzclient given that libgazebo installs both.

Speaking of the future of gazebo repo: https://github.com/osrf/docker_images/issues/354

**Comment by mikaelarguedas** [comment]
They're actually separate packages, at least for all the currently non EOL distros.

See https://github.com/osrf/docker_images/pull/355 for a set of gzclient images properly building.

The Debian Stretch one may not be as useful as nvidia doesnt provide an opengl images for debian buster.

**Comment by mikaelarguedas** [comment]
As the official images `gzserver*` and `libgazebo*` provide a full gazebo install with both server and client, I agree that we can discard the idea of building gzclient images :+1:
