### ISSUE TITLE
Detect base image changes and trigger dockerhub rebuilds

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#362]
Follow-up of https://github.com/osrf/docker_images/pull/312#issuecomment-544197023

Since Dockerhub stopped triggering repos that are using official images as base image.
Autobuilds are also disabled due to dockerhub not taking the image layer tree into account for building causing e.g. `desktop-full` image being built before `desktop`. 
As a result images in `osrf/ros` are never triggered other than manually.

## Feature request:
- Detect if any currently active image is outdated
- Trigger rebuild of impacted images

### Logic:
- Get the list of currently active images
- detect if their base image is in "osrf" or "library" org
- if base image in library: get the digest of base image
- verify that the digest of base image is in the layer list of current image
- if not: image outdated, trigger rebuild

### Implementation details:
- list of active images and their base images can be inferred from a combination of manifest.yaml + images.yaml.em + platform.yaml.
- Getting digests from dockerhub without pulling the images is not convenient with dockerhub API but can be done using something similar to https://stackoverflow.com/questions/41808763/how-to-determine-the-docker-image-id-for-a-tag-via-docker-hub-api/41830007#41830007

**Comment by ruffsl** [comment]
Related reading:

Keeping Up with Docker Official Images - https://blog.atomist.com/keeping-up-with-docker-official-images/
https://news.ycombinator.com/item?id=27436850

**Comment by mikaelarguedas** [comment]
Fixed in https://github.com/osrf/docker_images/pull/598
