### ISSUE TITLE
nightly and nightly-rmw are now the same + should we keep skipping opensplice rosdep keys?

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/docker_images#380]
Since CycloneDDS is in the `ros2:nightly` image and Opensplice is not in the nightly archives anymore.

`ros2:nightly` and `ros2:nightly-rmw` are now the same images.

We should either remove `ros2:nightly-rmw` or keep it but update the README accordingly.

Along with that we can revisit all the mentions of opensplice that remain:
- In the [skip-keys of nightly image](https://github.com/osrf/docker_images/blob/58f2e8a1d7bcf64cbe7ff0de936d58d4130eb918/ros2/nightly/images.yaml.em#L39):
  - pro-removal: if the image is built witch default args, skipping the key is unnecessary as ROS 2 doesnt ship with opensplice anymore'
  - con: anyone using an older archive will get `libopensplice` installed via rosdep while it was not the case before
- In the [source images Dockerfile](https://github.com/osrf/docker_images/blob/58f2e8a1d7bcf64cbe7ff0de936d58d4130eb918/ros2/source/images.yaml.em#L50)
  - pro/cons same as abobe, based on which distro people build from source they will or will not need to skip these keys

@ruffsl FYI

**Comment by mikaelarguedas** [comment]
> Is CycloneDDS a default rmw?

It depends what the definition of default is..

From my perspective the "default" is whatever is used when I launch a node without specifying `RMW_IMPLEMENTATION` explicitly. So right now this is Fast-RTPS and not CycloneDDS.

The nightly archive includes ALL rmw_*_cpp packages.
Only the system dependencies are not included. For opensplice is was the `libopensplice*` package.
Now both Fast-RTPS and CycloneDDS are built from source (no debs provided by vendor). So both of them are part of the nightly archive.

This means there is currently no "Not in the archive but open source" supported DDS implementations.

**Comment by ruffsl** [comment]
> Now both Fast-RTPS and CycloneDDS are built from source (no debs provided by vendor). So both of them are part of the nightly archive.

Ah, gotcha. I was thinking it was still a separate deb.

Ok, are there still any other rwm implementations that could sit in the rmw tag, like that shared memory transport from Bosch?

**Comment by mikaelarguedas** [comment]
AFAICT there are only 3 RMWs in the archive: fastrtps, cyclonedds and connext and it looks like it'll stay like this for now based on the REP for foxy https://github.com/ros-infrastructure/rep/pull/217/files

iceoryx is not part of the repos file at the moment. And as under heavy development my guess is that is would be built from source and not installed from deb if it was one of the officially supported rmws

**Comment by mikaelarguedas** [comment]
Adressed in https://github.com/osrf/docker_images/pull/383
