### ISSUE TITLE
[question] Unknown CMake command "rosidl_genarate_interfaces"

### ISSUE THREAD

**Issue by lx852357** [osrf/docker_images#384]
**environment:**
[ros1-bridge-docker](https://github.com/osrf/docker_images/tree/master/ros/eloquent/ubuntu/bionic/ros1-bridge) 

**description**
 I want bridge custom data type between ros1 and ros2. And I following the [tutorial](https://index.ros.org/doc/ros2/Tutorials/Custom-ROS2-Interfaces/) to compile custom message and report this error. I did't find anyone on Google who had the same problem. Hope to be answered, thank you!

**Comment by ruffsl** [comment]
> If you would like to use a bridge with other interfaces (including your own custom types), you will have to build the bridge from source
> https://github.com/ros2/ros1_bridge

The Dockerfile you link to installs the bridge from prebuilt debians that is only compiled with standard  built-in message types, and so is not applicable for bridging custom message types.

For more info on using the bridge, you may also want to look through the recent ROSCon talk for it:
* https://roscon.ros.org/2019/talks/roscon2019_bridging_ros1_to_ros2.pdf
* https://vimeo.com/379127737
* https://roscon.ros.org/2019/
