### ISSUE TITLE
Fatal Python error with ros2 cli when used inside privileged containers

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#385]
When using the ros2 cli inside a privileged container, a fatal python error will occur where the `encodings` module will not be found. As a minimal example:

``` shell
$ docker run -it --rm --privileged ros:eloquent ros2 --help
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fadcc843740 (most recent call first):
```

Privileged containers are useful in ROS when launching sensor driver nodes that require extensive device access to connect to external hardware and when the docker `--device` flag may not suffice.

I know this wasn't been an issue before, but it seems something may have changed in docker or how privileged containers are created. This doesn't seem to adversely affect ros1 though:

```
$ docker run -it --rm --privileged ros:melodic rosrun
Usage: rosrun [--prefix cmd] [--debug] PACKAGE EXECUTABLE [ARGS]
  rosrun will locate PACKAGE and try to find
  an executable named EXECUTABLE in the PACKAGE tree.
  If it finds it, it will run it with ARGS.
```

Here are some stats for the setup I'm seeing this error:

<details>

```
$ docker -v
Docker version 19.03.8, build afacb8b7f0

$ uname -a
Linux ubuntu 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 104
  Running: 0
  Paused: 0
  Stopped: 104
 Images: 406
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ums2ww7s78ls4q56hdwhofvzm
  Is Manager: true
  ClusterID: vfkhhzqomw4mndqqx6ngomfwo
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.157.150.14
  Manager Addresses:
   10.157.150.14:2377
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-40-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.19GiB
 Name: dox
 ID: T3AG:GNKQ:MRDN:LHYM:G2ZW:B6H3:PFSW:BMPH:L6IC:JDWZ:HZZR:DX7U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

@dirk-thomas @mikaelarguedas , perhaps you might know how the python environment is affected.

**Comment by mikaelarguedas** [comment]
> perhaps you might know how the python environment is affected.

I don't know how the Python env is impacted by the flag, didnt see anything related to python in the docker related docs either.

Thanks for providing more details about your setup.
IIRC you faced the same issue in the past and after re-pulling the images you couldn't reproduce it.

I updated my version of docker to match yours and can't reproduce on my side.

Can you confirm on what ros and ros2 images it fails (if it's like all ros2 images or just the eloquent one) and what is the digest of the failing ones?
Can you confirm the content of the following variables `PYTHONPATH` and `PYTHONHOME` in the failing ones.

**Comment by ruffsl** [comment]
> IIRC you faced the same issue in the past and after re-pulling the images you couldn't reproduce it.

I must have forgotten. I had the chance to test this on a separate host this morning, and yep, can't reproduce. Perhaps this is only specific to my Linux install on my laptop. Still a bit strange it doesn't effect both ROS1 and ROS2 python commands equally though.

> Can you confirm on what ros and ros2 images it fails (if it's like all ros2 images or just the eloquent one) and what is the digest of the failing ones?

It was also failing on all of the ROS2 images I tried, from crystal, up to eloquent.

```
$ docker pull ros:crystal
crystal: Pulling from library/ros
Digest: sha256:0489756a6abe52e43a55591a0164744c4b283b7cf8a2aa1a54d832541911d77b
Status: Image is up to date for ros:crystal
docker.io/library/ros:crystal

$ docker pull ros:dashing
dashing: Pulling from library/ros
Digest: sha256:af5a737150f0672d2d0c7c9c7ab70c928832bfaccf43be427a09291daa82547b
Status: Image is up to date for ros:dashing
docker.io/library/ros:dashing

$ docker pull ros:eloquent
eloquent: Pulling from library/ros
Digest: sha256:880957eb44e6a0f18d965203ab8f31109927877c4bf23791b20dcb46aa6ffd86
Status: Image is up to date for ros:eloquent
docker.io/library/ros:eloquent
```

> Can you confirm the content of the following variables PYTHONPATH and PYTHONHOME in the failing ones.

Let me get back to you on that and I'll get an env dump.

**Comment by ruffsl** [comment]
I can no longer reproduce this issue, so I'll close this for now.
