### ISSUE TITLE
Docker Images with shadow fixed packages

### ISSUE THREAD

**Issue by asmodehn** [osrf/docker_images#39]
Docker images for ROS are pretty useful.
In my case I use them in travis to test the code in a ROS environment.

One wish I would have though, is to have access to ros images that have been setup to use to ros shadow fixed repository, as the point of these images is to test latest packages (with latest dependent packages as well)

Maybe a set of extra "dev" images ?

**Comment by asmodehn** [comment]
Currently I am switching package repo in the docker container from travis script like this : https://github.com/asmodehn/pyros-utils/commit/6fae2ef289fa4e338f792d1d727639de18081102

But I do not upgrade all packages to latest (which could be useful in some usecases). I only rely on the dependencies of my tested package to be updated to shadow-fixed latest, via rosdep call.

**Comment by asmodehn** [comment]
After thinking a bit about this, maybe it doesn't make so much sense to do all the work to build docker images, when a few lines in a build script would suffice to upgrade all packages to latest...
Closing...

**Comment by davetcoleman** [comment]
+1... I'd be interested in having a shadow-fixed docker image myself, one that was updated more frequently than just when the Ubuntu image is updated

**Comment by ruffsl** [comment]
@davetcoleman , I'f you have an idea on what you'd like docker file to look like and how you'd like to automate the triggering for DockerHub builds, we could try hosting it experimentally under OSRF's profile.

**Comment by davetcoleman** [comment]
It could be triggered by the ``rosdistro`` repo - that would be very often! I don't know how to use their webhook feature though. The Dockerfile itself is easy to make - set the apt-list to shadow-fixed and install ros-base/ros-core

**Comment by ruffsl** [comment]
Short of a merged PR to the upstream official library index with ROS specific changes (which are relatively infrequent), the the official ROS image repo only triggers from the upstream Ubuntu repo. So automated builds under OSRF's ROS repo also trigger at the same frequency (although the OSRF repo also triggers upon pushes here to master branch, so that might be enough).

**Comment by davetcoleman** [comment]
I've run into this issue again here: https://github.com/ros/ros_comm/issues/904#issuecomment-249076202

I'm not sure what you are trying to say in your previous comment. I need shadow-fixed images that are updated on a more frequent basis, I guess I will just roll my own images on top of the Ubuntu image.
