### ISSUE TITLE
curl missing

### ISSUE THREAD

**Issue by flixr** [osrf/docker_images#407]
Nice job slimming down the images!

However curl is now missing and all our CI jobs are failing...
We could of course first install curl (which we need to get a GPG key), but this means another apt update && apt install before installing the normal packages which adds significant time to our builds.

Would be great if curl could be added to ros-base like git, rosinstall, ...

**Comment by mikaelarguedas** [comment]
oh that's unfortunate.
I don't remember seeing it in the diff of packages https://github.com/osrf/docker_templates/pull/82#issuecomment-596096052, and it doesnt seem to be installed in older images either:

```
# docker run -it --rm ros:indigo-ros-base
# curl
bash: curl: command not found
# apt update
# apt list --installed | grep curl
libcurl3/trusty-updates,trusty-security,now 7.35.0-1ubuntu2.20 amd64 [installed,automatic]
libcurl3-gnutls/trusty-updates,trusty-security,now 7.35.0-1ubuntu2.20 amd64 [installed,automatic]
```

Are you sure curl was coming bundled in the ros-base image and not in any of the additional steps of your dockerfiles ?
Do you have a sample dockerfile that used to work with older images and faisl with the new ones? 

---

Overall it's a reasonable request and I expect many people to need curl in that image.
I'm just being conservative and curious as of how / why it was not a problem before and we didnt notice the removal

**Comment by flixr** [comment]
We are actually using `ros:melodic-perception` to speed up build times (since in most cases we need OpenCV and pcl anyway) and I guess it was a recommended package of something in there.

The suggestion to put it in ros-base was just because that is where the other baisc devel tools are now added.

**Comment by ruffsl** [comment]
I'm not sure we could accommodate every 3rd party utility that crops up (even if curl is a common one). I think a better or more scalable approach is to use the official ros library images as a base image for your own CI images where one can install any number of custom dependencies, even as your CI pipeline evolves over time.

This is something that both nav2 and MoveIt2 do for CI, as there are a number of external quality of life dependencies are installed for CI runtime. Note that building such CI images at job time is unnecessary, as they can be pre-build and pushed via cron job as needed.

* https://github.com/ros-planning/navigation2/blob/76a7ab863f0571791c33b7f85afae2782e312944/Dockerfile#L47-L66
* https://github.com/ros-planning/moveit2/blob/fd3f70d7ec3c4e1feaa8634af65da025bd984b51/.docker/ci/Dockerfile#L2

**Comment by flixr** [comment]
Yes, we did something similar in the meantime...
For many of our builds, packages that we wanted to have pre-installed in the docker image were already there in the distro-perception images.
We "only" extra debian packages that we needed to install were those from our own internal testing/stable repo, which we need to fetch every time anyway to have the latest version.

In any case we can close this issue...
