### ISSUE TITLE
How to connect ros master from a  ros docker container

### ISSUE THREAD

**Issue by jacknlliu** [osrf/docker_images#41]
Assume I have a host machine "Slave" with IP: 192.168.1.123, and host machine "Master" with IP: 192.168.1.124.
A docker container with IP 172.17.0.2 on host machine "Slave", and a container with IP 172.17.0.2 on host machine "Master".

Then how to overcome the following two questions with some configurations:

- connect to host machine "Master" with roscore running (no docker container used) from a ros docker container on host machine "Slave"

- connect to a ros docker container with roscore running on host machine "Master" (roscore running in the docker container) from a ros docker container on host machine "Slave".

Any help will be appreciated!

**Comment by ruffsl** [comment]
This is similar to a question I asked and then found an answer to on ROS Answers:
 [Exposing ROS Containers to Host Machine](http://answers.ros.org/question/228292/exposing-ros-containers-to-host-machine/)

The addition challenge you pose is accessing the container from outside the host's local bridge network (and without port forwarding individual ports via exposing them through the host's own IP address). Basically exposing the software defined network to external subnets. similar question:
[How to connect nodes in docker to remote master?](http://answers.ros.org/question/244587/how-to-connect-nodes-in-docker-to-remote-master/?comment=245754#post-id-245754)

I'm not yet sure of the best way yo do this, but my gut instinct tells me this it already been done, or at least docker's libnetwork repo would have a feature request for it.
[Docker 1.10 container's IP in LAN](http://stackoverflow.com/a/36470828)

**Comment by jacknlliu** [comment]
I still try it. Thank you very much!

**Comment by jacknlliu** [comment]
A very powerful tool [weaveworks/weave](https://github.com/weaveworks/weave) provides an elegant and powerful solution for this issue.
