### ISSUE TITLE
/ros_entrypoint.sh: line 6: exec: test13: not found 

### ISSUE THREAD

**Issue by ishaniis** [osrf/docker_images#424]
I was just simply trying to run the ros-melodic-core image
using 
docker run -it ros:melodic-ros-core test13 
It doesn't run smoothly and gives away error
Error 1:
/ros_entrypoint.sh: line 6: exec: test13: not found
Error 2:
/opt/ros/melodic/etc/catkin/profile.d/10.roslaunch.sh: line 3: ROS_MASTER_URI: unbound variable

How to solve this?
Should I blind mount this file using -v? I'm a little clueless as to how to solve this error!

**Comment by mikaelarguedas** [comment]
Can you clarify what you are trying to accomplish ?

What is the command `test13` ?

Does the container start properly if you don't add the `test13` command?
```
docker run -it --rm ros:melodic-ros-core
```

**Comment by ishaniis** [comment]
Yeah, it's running. Thanks for that. I am basically trying to deploy the ROS cluster on Kubernetes both single-node and multi-node clusters. I made dockerfile for the same, I thought there is a problem with the image. Now, I guess there is a problem with my docker file. Could you help me with this docker file to find out the problem in the dockerfile. 

```
ARG from=ros:latest
FROM ${from}

RUN apt-get update &&\
    apt-get install -y \
        net-tools \
        iputils-ping \
        dnsutils \
    &&\
    rm -rf /var/lib/apt/lists/*

COPY ros_entrypoint.sh /usr/local/bin/ros_entrypoint.sh

RUN  chmod 755 /usr/local/bin/ros_entrypoint.sh

ENTRYPOINT ["/usr/local/bin/ros_entrypoint.sh"]
CMD ["bash"]

```
When I build this image
docker build . 
and I try testing it using -
docker run -it --rm <Image Name>
Error: 
 Executing master image entrypoint ...
-> Setting up ROS
/opt/ros/melodic/etc/catkin/profile.d/10.roslaunch.sh: line 3: ROS_MASTER_URI: unbound variable

Ending up giving crashloopbackoff error in my Kubernetes deployment.

**Comment by mikaelarguedas** [comment]
My guess is that it comes from the `set -u`
Does it work if you remove that line from your entrypoint ?

---

another surprising thing is that you base your images on `ros:latest`, but ros:latest is not ROS1 Melodic, it is ROS 2 foxy and as ROS 2 doesnt have a master, ROS_MASTER_URI does not exist.
As a note we usually recommend people to use explicit tags as base images and not the `latest` tag as the latest tag changes each time a new LTS distribution comes out.

**Comment by ruffsl** [comment]
Also, when replacing the entry point, make sure the script is excitable (`chmod +x ./ros_entrypoint.sh`) either in the source controlled file in your repo or at build time in the Dockerfile.

**Comment by ishaniis** [comment]
Thanks, ROS Master was deployed successfully and it's running after set -u was removed.
But would love to know the logic behind it? 
But somehow, just to check the cluster I deployed one talker and listener to initial deployment. 
They are still failing with crashloopbackoff error

**Comment by ruffsl** [comment]
I think the back off in ROS1 was from when they fail to connect to the master/roscore.
You may want to check how you are orchestrating your nodes in the containers. Perhaps take a look at this:

* https://answers.ros.org/question/253832/docker-how-to-make-sure-nodes-start-after-master/
* https://github.com/docker-library/docs/blob/c86a44ca7ecec1f047cfe32495cb0006b642b155/ros/content.md#compose

**Comment by mikaelarguedas** [comment]
I'm going to close this for inactivity and invite OP to post questions at more appropriate fora (like [ROS answers](http://answers.ros.org)) for wider visibility  in the future
