### ISSUE TITLE
docker's images don't work

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [osrf/docker_images#447]
Dear all,

### Problem

Assuming I have `./ros_entrypoint.sh` (still not clear why you should force the host machine to have such file) in my current working dir and I run

```
docker run \
    --rm \
    -it \
    ros:melodic-ros-core 

```

I get the following error

```
/ros_entrypoint.sh: line 6: exec:  : not found
```

Maybe the `WORKDIR` command was not setup correctly?

### Info

Docker version `2.3.0.4`

Best Regards,

Francesco

**Comment by LanderU** [comment]
Hi @FrancescoSaverioZuppichini,

it works for me out of the box:

```bash
lander@landeru-pc:~$ docker run --rm -it ros:melodic-ros-core
Unable to find image 'ros:melodic-ros-core' locally
melodic-ros-core: Pulling from library/ros
f08d8e2a3ba1: Already exists 
3baa9cb2483b: Already exists 
94e5ff4c0b15: Already exists 
1860925334f9: Already exists 
ddaa5f3004b4: Pull complete 
e61a1a213ee0: Pull complete 
27f2e3eccb0c: Pull complete 
299cf6e0456e: Pull complete 
e5b82098ee61: Pull complete 
d598c779a178: Pull complete 
Digest: sha256:a8604261bd22093b35225d1ee9287d18ce84d2b36dd1ea038b3170ba94b49734
Status: Downloaded newer image for ros:melodic-ros-core
root@91735ff79a11:/# cat /ros_entrypoint.sh 
#!/bin/bash
set -e

# setup ros environment
source "/opt/ros/$ROS_DISTRO/setup.bash"
exec "$@"
```

Note that when the image was built, ros_entrypoint.sh was copied to the image and is used as an ENTRYPOINT on the resultant docker image:

* https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/ros-core/Dockerfile#L36
* https://github.com/osrf/docker_images/blob/master/ros/melodic/ubuntu/bionic/ros-core/Dockerfile#L38

You don't need to have locally this file: https://github.com/osrf/docker_images/tree/master/ros/melodic/ubuntu/bionic/ros-core

**Comment by ruffsl** [comment]
This looks to be a misunderstanding of how entry points work in docker and not an issue with the Dockerfile.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you! Actually, I have just re-run the command that was causing the error before and now it is working. I am wondering what caused the problem in the first place!
