### ISSUE TITLE
Foxy images are outdated

### ISSUE THREAD

**Issue by ipa-mdl** [osrf/docker_images#453]
The current Foxy images are already two syncs behind.
What is the update policy for Foxy?
Is it a manual process? Or did some automated job fail?

**Comment by ruffsl** [comment]
The official library images are rebuilt whenever the Dockerfiles for the relevant tags are updated, or when the base image for such tag is updated. Looks like the Ros foxy tags for amd64 where rebuilt 14 days ago as of writing. Has there already been two public syncs to foxy within that time window?

We'd like to update the Dockerfiles upon each sync release using installed package sha with automated cron jobs, as sync don't normally change the pinned package versions. But it'll take some time implementation, and current maintainers are volunteers with their spare time.
Please see this is you'd like to help contribute.
https://github.com/osrf/docker_images/issues/376

**Comment by ipa-mdl** [comment]
> Looks like the Ros foxy tags for amd64 where rebuilt 14 days ago as of writing. 

Ah, yes you are right. I just had a look at the commit (https://github.com/osrf/docker_images/blob/30496b03a10f37d3ee54d5df672a0c27e0ab3952/ros/foxy/ubuntu/focal/ros-base/Dockerfile).

So only the last sync is missing, which was  announced 6 days ago..
And it did not change the ros_core version, but introduced some API changes.

I will have a look at #376

**Comment by mikaelarguedas** [comment]
Addressed by https://github.com/osrf/docker_templates/pull/90, example or resulting automatic PR: https://github.com/osrf/docker_images/pull/459

thanks @ipa-mdl !
