### ISSUE TITLE
Gazebo 8 missing curl

### ISSUE THREAD

**Issue by vectorcrumb** [osrf/docker_images#46]
I tried setting up a container with Gazebo 8 running:
```
$ docker run -d -v="/tmp/.gazebo/:/root/.gazebo/" --name=gazebo gazebo:gzserver8
$ docker exec -it gazebo bash
```
However, when I tried to use curl to run the examples in the docs at the [Docker Hub](https://hub.docker.com/_/gazebo/), I get an error that curl can't be found
```
root@7255c42889e8:/# curl
bash: curl: command not found
```

**Comment by tfoote** [comment]
I'd suggest that we update the tutorial to apt-get install curl before using it. Instead of increasing the size of the base image since the curl is a convenience method for pulling in a model specific to the example. The docs are here: https://github.com/docker-library/docs/blob/master/gazebo/README.md

**Comment by vectorcrumb** [comment]
In the meanwhile, could I modify the corresponding Dockerfile to install curl during the build process?

**Comment by tfoote** [comment]
If you have a local copy yes. However as I mentioned above we shouldn't add it into the packaged version. If you are building a custom application on top of the base on docker hub you should write a dockerfile that uses the ones we provide as the FROM target and adds what you need on top (like curl) in your own custom layers.

**Comment by ruffsl** [comment]
@vectorcrumb , you could write child image to add what you need, then use that image instead.
I do this all the time to bootstrap my personal dev tools from a basic base image, e.g:

``` dockerfile
FROM gazebo

# Get helpful dev dependencies
RUN apt-get update && \
    apt-get install -y \
      curl \
      wget \
      screen \
      byobu \
      fish \
      git \
      nano \
      vim \
      glances \
      bash-completion \
      less \
      tree
```

@tfoote , I'll start a PR to the docs to update the `apt-get install curl` instructions though.

**Comment by ruffsl** [comment]
Documentation has been updated to reflect this, closing for now.
