### ISSUE TITLE
how to properly set up docker-compose for ROS networking with host

### ISSUE THREAD

**Issue by waspinator** [osrf/docker_images#48]
I'm trying to follow the[ Small ROS Network Example](https://gist.github.com/ruffsl/4a24c26a1aa2cc733c64) to set up a docker+ROS network, but I'm having trouble `netcat`ing between machines. Just running the docker file as-as I can `rostopic echo /chatter` and get the correct output, but trying to `netcat` fails. The wiki says that every port has to be open for ROS to work, but I'm not seeing any `EXPOSE` or `-p` commands, so I'm not sure how that's supposed to work. Shouldn't you need to have `EXPOSE 0-65535` and `-p 0-65535:0-65535`?

When I `exec` into  the master and install and run `netcat -lv 4444` I get an error: 

    4444: inverse host lookup failed: Unknown host
    listening on [any] 33534 ...

and then when I try to `echo Hello World | netcat 172.20.0.2 33534` I see this error on the master

    172.20.0.1: inverse host lookup failed: Unknown host
    invalid connection to [172.20.0.2] from (UNKNOWN) [172.20.0.1] 33534

It works if I do it the other way though, listening on the host, and echoing from the master container.

...

hmm when, I add the `-p` flag to `netcat` in the master container, it doesn't complain anymore about `inverse host lookup`, and I can `echo` `netcat` into it from the host. But I'm still having issues connecting a ros action client from the host to an action server in a container. When I try to connect I get a `Couldn't find an AF_INET address for [docker-host]` message come up. I can get rid of that by setting my host's `ROS_IP=192.168.198.128` (the first address which comes up after a `hostname -I` command), but the client still doesn't communicate with the server correctly.

I also sometimes get errors from resolvable, but when they do happen, restating docker-compose gets rid of them.

    resolvable_1  | 2017/02/06 20:01:03 response error: *net.OpError read udp 127.0.0.11:53: i/o timeout

and `roswtf` gives the following warning:

    WARNING The following node subscriptions are unconnected:
        * /robot_plan:
           * /robot_plan/goal
           * /robot_plan/cancel

    WARNING The following nodes are unexpectedly connected:
     * /robot_plan->/rostopic_120859_1486412001446 (/robot_plan/feedback)
     * /robot_plan->/rostopic_120887_1486412009716 (/robot_plan/result)

**Comment by waspinator** [comment]
I made an example actionlib configuration which doesn't work, but I'm not sure why.

https://github.com/waspinator/ros-docker-examples/tree/master/actionlib-fibonacci

**Comment by ruffsl** [comment]
Hmm, thanks for the example test case @waspinator . I'll investigate when I get some time.

**Comment by jacknlliu** [comment]
@waspinator  I think you need [weave-net](https://github.com/weaveworks/weave#weave-net), please see https://github.com/weaveworks/weave/issues/1829.

**Comment by ruffsl** [comment]
Well, I went back to your actionlib docker-compose example, and I'm still not sure whats missing... However, if your fine with laxing the issue and having the container share the host's network interface, this docker-file works in your linked example instead:

``` yaml
version: '2'

services:
  master:
    build: .
    network_mode: "host"
    command: roscore

  fibonacci:
    build: .
    network_mode: "host"
    command: rosrun actionlib_tutorials fibonacci_server
```

Related: [How to have topics publish and subscribe both ways between host and docker container?](https://answers.ros.org/question/298602/how-to-have-topics-publish-and-subscribe-both-ways-between-host-and-docker-container/?answer=298636#post-id-298636) . Closing for now.
