### ISSUE TITLE
should use datetimectl?

### ISSUE THREAD

**Issue by rotu** [osrf/docker_images#480]
Many files here edit system files to manipulate the timezone. It would probably be better to use `timedatectl` on Ubuntu Xenial or later:

this:
```
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
```

can be replaced with the more succinct:
```
timedatectl set-timezone UTC
```

provided that `tzdata` is installed first.

**Comment by ruffsl** [comment]
> Ubuntu Xenial or later

We've just been using one set of docker .em templates to reduce the amount of corner case logic. But if you can verify your change works for all non-EOL ROS/Gazebo tags, then feel free to open a PR here and on osrf/docker_templates.

**Comment by rotu** [comment]
@ruffsl I figured it was something like that. I don't think I understand the infrastructure enough to make this change (what tags are/are not EOL? Why are some releases in https://github.com/osrf/docker_templates/blob/adad8152da75670c9a157102b322770a931c6b2a/docker_templates/templates/snippet/setup_tzdata.Dockerfile.em#L2-L4 and not others? What's the proper way to test a change for osrf/docker_templates and/or osrf/docker_images - is CI sufficient?)

**Comment by ruffsl** [comment]
> what tags are/are not EOL?

You can view the manifest files to see which tags have been commented out given there EOL date:

https://github.com/osrf/docker_images/blob/b98f6fde642f65bce1b881a0e90a334c6b3eb8da/ros/manifest.yaml#L103-L104

https://github.com/osrf/docker_images/blob/b98f6fde642f65bce1b881a0e90a334c6b3eb8da/ros/manifest.yaml#L113-L115

> Why are some releases in releases_with_configured_tzdata and not others?

Looking at the git blame, https://github.com/osrf/docker_templates/pull/34 reminds us that ubuntu:bionic docker image no longer ships with tzdata pre-installed. So setting tzdata would have to occur after it's installment.

> What's the proper way to test a change for osrf/docker_templates and/or osrf/docker_images

I normally install the python packages that the CI would require, then append the cloned docker_template repo to my local python path, and use the docker_image scripts to experiment with the templates locally. E.g:

* https://github.com/osrf/docker_images/tree/master/docker
* https://github.com/osrf/docker_templates/blob/master/setup.bash
* https://github.com/osrf/docker_images/blob/master/ros/create_dockerfolders.py

```
cd ros
./create_dockerfolders.py --help
./create_dockerfolders.py dir -d ./ -a
```

**Comment by rotu** [comment]
> > Why are some releases in releases_with_configured_tzdata and not others?
> 
> Looking at the git blame, [osrf/docker_templates#34](https://github.com/osrf/docker_templates/pull/34) reminds us that ubuntu:bionic docker image no longer ships with tzdata pre-installed. So setting tzdata would have to occur after it's installment.

Oooooh. I totally misunderstood this code!

My understanding was that the purpose of the code was to set the timezone to UTC and tzdata was needed for that to be respected.

But judging by osrf/docker_templates#34, I got that entirely backwards. The reason we're setting up timezone to UTC is because packages eventually need `tzdata` and we want to suppress interactive prompts when it is later installed.

We can't call `datetimectl` before installing `tzdata` because the timezone is unknown to the system. (the way we do it now, `ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime` creates a dangling symlink, but it's good enough to make tzdata consider itself already configured, and it's no longer dangling after tzdata is installed.
