### ISSUE TITLE
ROS2 foxy publish/subscribe between Docker container and Windows host

### ISSUE THREAD

**Issue by anastasiapan** [osrf/docker_images#509]
Currently I have ROS2 foxy on a docker container and what I want to do is to publish and subscribe from the container to Windows side and the other way around as well. The installation I followed for ros2 foxy on windows is the official one (https://index.ros.org/doc/ros2/Installation/Eloquent/Windows-Install-Binary/). Right now I am testing with ros2 examples (minimal publisher and minimal subscriber (https://index.ros.org/r/examples/) . I have tried to do this between two separate containers and it just works out of the box.

One thing I tried but didn't fix is to change the RMW_IMPLEMENTATION to eProsima (https://index.ros.org/doc/ros2/Concepts/DDS-and-ROS-middleware-implementations/). It should be the default value though. Having said that I am not at all experienced with DDS.

`set RMW_IMPLEMENTATION=rmw_fastrtps_cpp`

I have also tried to run the docker image with host network as below: 
`docker run -it --name some_name --network="host" container`

**Comment by ruffsl** [comment]
This might be a question better asked on answers.ros.org, but can you verify multicast traffic can traverse the network bridging between the windows host and docker VM?

Related? https://github.com/docker/for-win/issues/6736

**Comment by anastasiapan** [comment]
I have tried this and it works so I believe it has to do with ROS and specifically with Windows host-Ubuntu container combo. Because if you publish between Ubuntu container-Ubuntu host it works just fine. I posted on ros answers too but I thought to post here too so people who will see it use specifically ROS on docker container. Thanks for  your answer.

**Comment by tfoote** [comment]
Please don't cross post questions, that just clutters up things for future searches. If you do at least cross link so that people who find one can find the other. Since answers.ros.org is the right place I'm going to close this. Please comment back here with a link to your answers.ros.org post to help others who might search and find this duplicate post instead of the answers.ros.org post.

**Comment by anastasiapan** [comment]
@tfoote This is the ros answers link https://answers.ros.org/question/369895/ros2-foxy-publishsubscribe-between-docker-container-and-windows-host/
