### ISSUE TITLE
flake8 behavior is different from setup-ros

### ISSUE THREAD

**Issue by kenji-miyake** [osrf/docker_images#531]
I found flake8 behavior is different from [ros-tooling/setup-ros](https://github.com/ros-tooling/setup-ros).

This is because setup-ros installs flake8 plugins, but docker_images don't.

To check this, I intentionally wrote code with the wrong import order and test it on CI.
Followings are the test result.

Using setup-ros: Fail (correct behavior)
![image](https://user-images.githubusercontent.com/31987104/117354646-8ada2880-aeec-11eb-8c9a-58391c16fd3f.png)

Using docker_images: Pass (wrong behavior)
![image](https://user-images.githubusercontent.com/31987104/117354703-9fb6bc00-aeec-11eb-95c9-28ed9221e9ee.png)

Please see here for more details about the above images.
https://github.com/kenji-miyake/test_ros_ci_flake8/pull/1

Is this correct behavior?

**Comment by ruffsl** [comment]
I don't think flake8 ships with any of the current variant  meta packages provided by ROS. While the official library images do include some developer conveniences like colcon and some compilers and runtimes, you may want to build off your own child image to include more specific developer tools and CI dependencies.

**Comment by kenji-miyake** [comment]
Thank you.
So do you mean developers should do one of the followings?
- build a child image that includes flake8 plugins
- install flake8 plugins in CI script

It's fine but I just want to clarify it.

**Comment by ruffsl** [comment]
You could do either. Building a child image to pre-bake any dev dependencies could shorten setup for CI at runtime, but you'd want to periodically rebuild it to ensure your using an up-to-date parrent image. Or you could install dev-tools via the CI script, taking more time for CI setup but without the hassle of hosting your own up-to-date child image.

Some examples of both:

* child image
  * https://github.com/ros-planning/navigation2/blob/25fe2448f5d8badf7f021165cc85caf231dc20d7/Dockerfile#L40-L45
* ci script:
  * https://github.com/ruffsl/colcon-cache/blob/38f3c208625c82f3393cad879e95b43506dfbb02/.github/workflows/test.yml#L14-L21

The first does more than just installing dev tools, while the later also uses caching actions to compensate.

**Comment by kenji-miyake** [comment]
Thank you, I understand!

**Comment by kenji-miyake** [comment]
@ruffsl Please let me ask you one more thing. :bow: 
Is it a good idea to add flake8 plugins to rosdistro and add dependencies to ament_flake8 or another package in order to make CI scripts simple?

**Comment by kenji-miyake** [comment]
@ruffsl Thank you.
I meant flake8 **pluigins**, not flake8 itself. It's not in rosdistro now, so I'm considering to send a PR.
https://github.com/kenji-miyake/rosdistro/commit/f0cb72cf150d3178e242a6ef54e8f719327ee1f6

Concretely, adding the following dependencies to https://github.com/ament/ament_lint/blob/4bc68c815ce308b3443e3cb38fd71e2b03ffdc40/ament_flake8/package.xml.

```xml
  <test_depend>python3-flake8-blind-except-pip</test_depend>
  <test_depend>python3-flake8-builtins-pip</test_depend>
  <test_depend>python3-flake8-class-newline-pip</test_depend>
  <test_depend>python3-flake8-comprehensions-pip</test_depend>
  <test_depend>python3-flake8-deprecated-pip</test_depend>
  <test_depend>python3-flake8-docstrings-pip</test_depend>
  <test_depend>python3-flake8-import-order-pip</test_depend>
  <test_depend>python3-flake8-quotes-pip</test_depend>
```

**Comment by kenji-miyake** [comment]
I reopen this in order to discuss a bit more.

**Comment by ruffsl** [comment]
> Is it a good idea to add flake8 plugins to rosdistro and add dependencies to ament_flake8
> It's not in rosdistro now, so I'm considering to send a PR.

I'm not sure the maintainers for `ament_flake8` would ever want to include all those `test_depend`s into their package.xml, but adding those flake8 plugins to python index for rosdistro sounds logical. Not sure if rosdistro would prefer pip over apt, but open a PR to ask to suppose. 

> or another package in order to make CI scripts simple?

Yep, you could then write/add your own meta package into the repo/workspace to rope in any other test dependencies using `rosdep install` later on in CI. For example, nav2 has a non-released package, `nav2_system_tests`, that kind of does this.

https://github.com/ros-planning/navigation2/blob/d51c1fd15e6f0a5e9cb2f437fcc0e0e5612d2363/nav2_system_tests/package.xml#L57-L64

**Comment by kenji-miyake** [comment]
> I'm not sure the maintainers for ament_flake8 would ever want to include all those test_depends into their package.xml

Yes I know, so that's why I wrote `or another package`. It could be user's packages like `nav2_system_tests`.

> but adding those flake8 plugins to python index for rosdistro sounds logical. 

Okay, I'll send a PR!

> Not sure if rosdistro would prefer pip over apt

I believe these plugins are not released over apt. Anyway, will ask them on the PR.
