### ISSUE TITLE
Foxy/Galactic Image for ARM32v7

### ISSUE THREAD

**Issue by barnesew** [osrf/docker_images#556]
Would it be possible to get a ROS2 image for foxy or galactic that targets the ARM32v7 architecture? I leverage the ROS2 docker containers for my development and would love to use some of the newer features.

**Comment by mikaelarguedas** [comment]
TLDR: arm32 is not an officially supported platform so we cannot easily create docker images for it.


Only tier 1 platforms get binary packages that can be installed in docker images. As a result, for each ROS2 distribution, we provide only docker images for the tier 1 platforms listed in REP-2000, e.g. for [galactic](https://www.ros.org/reps/rep-2000.html#galactic-geochelone-may-2021-november-2022) only Ubuntu focal amd64 and aarch64. Arm32v7 being tier 3 (aka not officially supported) no image is provided for it
