### ISSUE TITLE
osrf/ros2:testing docker image not working

### ISSUE THREAD

**Issue by ijnek** [osrf/docker_images#560]
I posted a [Question](https://answers.ros.org/question/384277/osrfros2testing-docker-image-not-working/) on ROS Answers, but I'm raising an issue as I'm quite certain it's a bug in the generation of the testing docker image.

   Running:
  
      docker pull osrf/ros2:testing
      docker run -it osrf/ros2:testing
  
  Throws an error:
  
      /ros_entrypoint.sh: line 5: /opt/ros/rolling/setup.bash: No such file or directory

**Comment by ruffsl** [comment]
While the `osrf/ros2:testing` does include the same `ros_entrypoint.sh` script to keep it interchangeable with other ros image tags, it does not pre-install any ros specific packages, as it is intended to be used as a base image for child Dockerfiles that would install user specified ros dependencies. If you do want to spawn containers directly from the `osrf/ros2:testing` tag, you could override the default entrypoint by specifying a different one via the docker run arg:

```
docker run -it --rm --entrypoint="" osrf/ros2:testing
```

https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime

**Comment by ijnek** [comment]
That makes sense, I'll post your response in ROS Answers. Thanks!
