### ISSUE TITLE
Docker hub documentation out of sync with current container

### ISSUE THREAD

**Issue by kengregson** [osrf/docker_images#571]
Description in Deployment Example at https://hub.docker.com/_/ros states:

Notice that a new network named ros_demos has been created, as can be shown further with:
$ docker network inspect ros_demos

whereas actual network name created  by current ros:foxy image is:
ros-docker-demos_default

**Comment by mikaelarguedas** [comment]
Thanks for reporting the inconsistency :+1:

See https://github.com/docker-library/docs/pull/2071 for the update to the docs.
When I tried it the network was named `ros_demos_default`. Could you cllarify if this is the same for you or if you get ` ros-docker-demos_default` instead?

**Comment by kengregson** [comment]
Happy to help in any way. Using the docker-compose.yml in the description
(on an NVidia Jetson Xavier NX running Ubuntu bionic 18.04 with Docker
version 20.10.7, build 20.10.7-0ubuntu1~18.04.2), with this docker image:

$docker image ls
REPOSITORY                  TAG                IMAGE ID       CREATED
 SIZE
ros                         foxy               67520d943e5f   2 weeks ago
 611MB

The network is named "ros-docker-demos_default" as shown in:

$ docker-compose up -d
Creating ros-docker-demos_talker_1   ... done
Creating ros-docker-demos_listener_1 ... done

$ docker network ls
NETWORK ID     NAME                       DRIVER    SCOPE
6086ed497a33   bridge                     bridge    local
cf5d5330c268   host                       host      local
6c048b469499   none                       null      local
28e7935f0fd9   ros-docker-demos_default   bridge    local

$ docker network inspect ros-docker-demos_default
[
    {
        "Name": "ros-docker-demos_default",
        "Id":
"28e7935f0fd9e4534126f3a991716f34c818090ab0028bdecf4a9d7592b3967e",
        "Created": "2021-10-31T17:05:07.09208067-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {

"117dd1604b203c964ec95c57b98a86c719633bbbbaf5bd3bae6ab5af544b5a73": {
                "Name": "ros-docker-demos_talker_1",
                "EndpointID":
"fc2510e74816ecbe723e14927a0caa24344ef5ecbdee0820f89291e855b0b56e",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },

"bd79c00b9b2d63be9846209b58354ba0498b7b413a6404e3584d57ccd9cbd372": {
                "Name": "ros-docker-demos_listener_1",
                "EndpointID":
"59e2810796040662a1e6005e3d87bfb8a77aa5a84fe83df34a8520aef0d9b288",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "ros-docker-demos",
            "com.docker.compose.version": "1.29.2"
        }
    }
]

**Comment by ruffsl** [comment]
> ros-docker-demos_default

Looks like you named the folder for the compose file `ros-docker-demos` instead of `ros_demos`.
The docs seem to be consistent with what I'm seeing with the latest docker version.
