### ISSUE TITLE
Latest docker images (foxy, galactic) for arm32v7

### ISSUE THREAD

**Issue by jiyojolly** [osrf/docker_images#573]
The docker images available for arm32v7 are outdated. The latest version 'dashing' has reached EOF. 
The docker images for Foxy and Galactic should be included as they are supported natively in arm32v7.

**Comment by ruffsl** [comment]
If I recall correctly, debian binaries for Dashing and Foxy releases are not supported for the arm32 architecture.

https://www.ros.org/reps/rep-2000.html

**Comment by mikaelarguedas** [comment]
Indeed, starting with ROS Foxy, arm32 became a tier 3 platform so no debian packages are provided for that platform from Foxy onward: https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023
