### ISSUE TITLE
executor failed running rosdep init && rosdep udpate

### ISSUE THREAD

**Issue by Toernblom** [osrf/docker_images#575]
Hey, tried following this forum reply,
https://answers.ros.org/question/362335/unable-to-build-ros-foxy-for-armv7/

wanted to build ros2 for raspberry pi but getting these errors. Has the sources list changed, if so, to what?

` 
=> ERROR [ 9/15] RUN rosdep init     && rosdep update                                                                   3.2s ------
 > [ 9/15] RUN rosdep init     && rosdep update:
#12 3.104 ERROR: cannot download default sources list from:
#12 3.104 https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
#12 3.104 Website may be down.
------
executor failed running [/bin/sh -c rosdep init     && rosdep update]: exit code: 4
`

**Comment by ruffsl** [comment]
From the warning, it looks rosdep can't resolve an available package index for arm32v7 platforms:

```
$ git clone https://github.com/osrf/docker_images.git
$ cd docker_images/ros2/source/devel
$ docker build --tag arm32v7/ros2:devel \
    --build-arg=FROM_IMAGE=arm32v7/ubuntu:focal .
...
Step 12/21 : RUN rosdep init     && rosdep update
 ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 3b7aa856cf0c
ERROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.
The command '/bin/sh -c rosdep init     && rosdep update' returned a non-zero code: 4
```

I'm guessing this may have to do with that: https://github.com/osrf/docker_images/issues/573#issuecomment-960456619

**Comment by Toernblom** [comment]
Ah, right. Thanks!
