### ISSUE TITLE
Enable noetic desktop and desktop-full?

### ISSUE THREAD

**Issue by lucasw** [osrf/docker_images#582]
I see they are commented out here, could they be brought back?

https://github.com/osrf/docker_images/blob/master/ros/noetic/debian/buster/Makefile#L17-L18

(and presumably the `osrf/` part of the prefix is chopped of as in the other entries)

**Comment by sloretz** [comment]
It's the [same for ROS Melodic](https://github.com/osrf/docker_images/blob/85f686512bdfb0ddf2dd187d9aea95c9cebdfc0c/ros/melodic/debian/stretch/Makefile#L17). I think it has something to do with the images that are built for https://hub.docker.com/_/ros not being allowed to include GUIs, while the images in https://hub.docker.com/r/osrf/ros/ can.

**Comment by lucasw** [comment]
That no-gui policy is self-imposed?

I found this clue for kinetic, looks like melodic and kinetic were copied and pasted from it without additional comment

> Omitting the build of ros desktop from dockerfile CI build
> To keep reported CI errors pertinent to official ROS images

https://github.com/osrf/docker_images/commit/3e8b29c44f02c85b71a156be51c94902d4092929

**Comment by sloretz** [comment]
> That no-gui policy is self-imposed?

No, it was something imposed to become one of the [Docker "Official Images"](https://github.com/docker-library/official-images/blob/master/README.md#what-are-official-images), but I can't find it in the review guidelines. It maybe documented elsewhere, or may no longer be a rule.

**Comment by ruffsl** [comment]
> That no-gui policy is self-imposed?

I think this was something the reviewers requested when ROS and Gazebo images were first proposed:

https://github.com/docker-library/official-images/pull/855#issuecomment-120463298

**Comment by ruffsl** [comment]
Closing with https://github.com/osrf/docker_images/pull/588#issuecomment-1042236352
