### ISSUE TITLE
Seg fault in rolling-ros1-bridge

### ISSUE THREAD

**Issue by vincentrou** [osrf/docker_images#593]
The image `ros:rolling-ros1-bridge` from docker hub https://hub.docker.com/_/ros stop with segmentation fault when executing `ros2 run demo_nodes_cpp talker`

This is working on galactic and foxy tag.

**Comment by mikaelarguedas** [comment]
Thanks @vincentrou  for reporting, can you confirm if this is still the case ? (that image was rebuilt 4 days ago and I cant reproduce the issu on my machine)

**Comment by vincentrou** [comment]
Thanks @mikaelarguedas , it's working now.
