### ISSUE TITLE
Docker image of ros-noetic-desktop-full is the same as ros-noetic-desktop

### ISSUE THREAD

**Issue by borsasd** [osrf/docker_images#603]
Hi!

I have discovered that ros-noetic-desktop-full is actually just the ros-noetic-desktop image, and therefore not containing for example Gazebo, which should be in the desktop full image. As seen in the attached images, the last command of the full image is just installing the "desktop" package. Also, the digest is the same for the 2 images.
![ros-noetic-desktop-full-dockerhub](https://user-images.githubusercontent.com/23477552/154965843-be82e4f5-a21f-44ed-8c97-7f8d09c265a6.png)
![ros-noetic-dockerhub-digests](https://user-images.githubusercontent.com/23477552/154965847-e0234927-a9bc-4684-a5f8-7efd36663f89.png)

**Comment by ruffsl** [comment]
Thanks @borsasd for the reporting the issue! A fix has now been pushed.
