### ISSUE TITLE
Create images that are built from source

### ISSUE THREAD

**Issue by audrow** [osrf/docker_images#610]
It would be great for testing purposes if I could pull a Docker image that has been built from source, rather than just from debian pacakages.

**Comment by 130s** [comment]
I'm not entirely sure the intent of the OP though, the tool I'm making https://github.com/130s/docker_vcstool may help. No document at all (and it might be broken. This month I have a project where I need to get it working) ATM. It picks up a list of source repos defined in [vcstool](https://github.com/dirk-thomas/vcstool) manner, then build a Docker image.

**Comment by ruffsl** [comment]
While we do already have a set of Dockerfiles for building the ROS2 master branch from source:

https://github.com/osrf/docker_images/blob/687f5e9440f97e7cb00f1a227512d6e7929ecba1/ros2/source/source/Dockerfile#L21-L22

We also already have nightly images that are built using the nightly fat archives compiled by the ROS2 build farm:

https://github.com/osrf/docker_images#repo-info-3

https://github.com/osrf/docker_images/tree/master/ros2/nightly/nightly

While we have before considered using the local CI to rebuild and host a ROS2 source docker image:

https://github.com/osrf/docker_images/issues/294

This was however deemed as redundant given the nightly archive used for night tags are compiled from the same source. 

@audrow , do you have a use-case with a hosted source tag being preferential over the existing nightly tags?

**Comment by audrow** [comment]
> @audrow , do you have a use-case with a hosted source tag being preferential over the existing nightly tags?

@ruffsl, I didn't know the nightlies were built from source. Also, thanks for the context. I'm happy to use the nightlies. Two thoughts:

- It'd be nice to have an additional label for source, just for clarity. Especially if it is not difficult to add.
- It'd be great to have images built from source for past distros of ROS 2, not just rolling. I don't believe that I see this in the repo. This would be very useful for me as a developer on ROS as I could easily pull up a distro for testing when needed, without having to maintain a Dockerfile for each distro.

**Comment by audrow** [comment]
> I'm not entirely sure the intent of the OP though, the tool I'm making https://github.com/130s/docker_vcstool may help. No document at all (and it might be broken. This month I have a project where I need to get it working) ATM. It picks up a list of source repos defined in [vcstool](https://github.com/dirk-thomas/vcstool) manner, then build a Docker image.

@130s, seems like a cool tool. I've starred the repo. I'll check back on it periodically. Thanks for sharing!

**Comment by mikaelarguedas** [comment]
What would be included in the resulting image ? Would it be a full workspace with all the sources or just the install space ?

What version of each repo would be used ? whatever branch is listed in the repos file for each distro branch on ros2/ros2 ?

One concern I have is the duplication of effort and compilation time. It looks to me that the OSRF infrastructure already takes care of building all of ros2 from source, could either jenkins push a resulting docker image or the images here just leverage artifacts compiled by the jenkins instances ?

**Comment by audrow** [comment]
> What would be included in the resulting image ? Would it be a full workspace with all the sources or just the install space ?

My preference is the full workspace, specified by the repos file with all the sources and the install space.

> What version of each repo would be used ? whatever branch is listed in the repos file for each distro branch on ros2/ros2 ?

I would think whatever is the repos file for each currently maintained branch.

> One concern I have is the duplication of effort and compilation time. It looks to me that the OSRF infrastructure already takes care of building all of ros2 from source, could either jenkins push a resulting docker image or the images here just leverage artifacts compiled by the jenkins instances ?

That might be a good way to go about this.

---

Btw, I have my own local version here: https://github.com/audrow/ros2-docker/blob/master/from-src/Dockerfile.

**Comment by mikaelarguedas** [comment]
@androw Any news on this ? What is OSRF take about leveraging their existing builds to provide docker images with the content you seek ?

**Comment by mikaelarguedas** [comment]
Thanks! sorry for the typo :sweat_smile:

**Comment by audrow** [comment]
I'm not sure. I'll ping some other folks at Open Robotics to see if there's any news.

I'm not very involved in our efforts in this repo, so I'm not sure who the best people are to ask about this.

**Comment by mikaelarguedas** [comment]
Maybe @nuclearsandwich @tfoote has some insights on this topic?

**Comment by nuclearsandwich** [comment]
> * It'd be great to have images built from source for past distros of ROS 2

Since these are based on the ci.ros2.org artifacts, they target rolling's development branches via the ros2.repos file. We have not been building stable distributions from source since we provide deb/rpm binaries for these. It would be possible to create images which use the patch release artifacts, which are built "from source" but only updated on each patch release.

> [From source images for stable distributions] would be very useful for me as a developer on ROS as I could easily pull up a distro for testing when needed, without having to maintain a Dockerfile for each distro.

What are you testing here that requires being built from source rather than creating overlay workspaces.

As a side note, creating docker images that include source and build contents rather than the install space also means quite large (and thus cumbersome to distribute) image files.
One way that the Space ROS project mitigates this is by including the output of `vcs export --exact` in the generated image so that sources can be "rehydrated". That only works for sources in the workspace and not the versions that are provided by the operating system so it is not "perfect reproducibility" but still a good improvement on nothing.


Given that we're coming up on this issue's birthday @audrow how have you been meeting this need in the interim. Are you still maintaining your own suites of containers for this?

**Comment by audrow** [comment]
> I feel that what you're looking for is a quick workspace setup for validation

I agree with that.

> I'd like to understand if there's other options for providing the same functionality.

That seems reasonable to me.

**Comment by audrow** [comment]
@nuclearsandwich 

> Since these are based on the ci.ros2.org artifacts, they target rolling's development branches via the ros2.repos file. We have not been building stable distributions from source since we provide deb/rpm binaries for these. It would be possible to create images which use the patch release artifacts, which are built "from source" but only updated on each patch release.

That'd be better, but a big part 

> > [From source images for stable distributions] would be very useful for me as a developer on ROS as I could easily pull up a distro for testing when needed, without having to maintain a Dockerfile for each distro.
> 
> What are you testing here that requires being built from source rather than creating overlay workspaces.

I suppose that I could probably almost always overlay the workspace. The main idea is to get an environment that's as similar to CI as possible, so that I can reproduce things easily. I believe that if I wanted to do that, I could have a ROS 2 workspace overlay that has basically all of the ROS 2 packages up to the package I'm working on. 
 
> As a side note, creating docker images that include source and build contents rather than the install space also means quite large (and thus cumbersome to distribute) image files. One way that the Space ROS project mitigates this is by including the output of `vcs export --exact` in the generated image so that sources can be "rehydrated". That only works for sources in the workspace and not the versions that are provided by the operating system so it is not "perfect reproducibility" but still a good improvement on nothing.

Sounds interesting.

> Given that we're coming up on this issue's birthday @audrow how have you been meeting this need in the interim. Are you still maintaining your own suites of containers for this?

I have been doing alright with making my own docker images in the meantime. I often just build a Dockerfile when I need one, since it seems like things may change between and it's hard to know what in the install process changed.

**Comment by audrow** [comment]
I'll close this issue for now since I don't have too much to add and my current workarounds are working fine. We can reopen this issue if there is more interest around the idea and if we come up with better solutions to the large images that would be required (maybe learn from SpaceROS) and the different workflows that might be solved with this Docker image.
