### ISSUE TITLE
no matching manifest for linux/arm64

### ISSUE THREAD

**Issue by JabSYsEmb** [osrf/docker_images#615]
is there any upcomming arm64 version docker image for gazebo ?

```
Using default tag: latest
latest: Pulling from library/gazebo
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by mikaelarguedas** [comment]
Not that I'm aware of. Cross-linking past thread about arm support: https://github.com/osrf/docker_images/issues/421

@chapulina I didnt find platform support on the Gazebo website. Do you know where one can find the status of arm64 support for different gazebo versions ?

**Comment by chapulina** [comment]
Here are some links for Gazebo support from Citadel onwards:

https://community.gazebosim.org/t/ignitions-supported-platforms/1210

For Gazebo classic, `arm` architectures fall in the best-effort support category, so we take contributions.

**Comment by mikaelarguedas** [comment]
As Gazebo classic is sunsetting and will not provide official arm support and as new gazebo distros seem to come with arm packages I'm going to close this.
The availability of docker images for new gazebo versions will be tracked here https://github.com/osrf/docker_images/issues/354
