### ISSUE TITLE
Rolling: apt-key deprecation warning

### ISSUE THREAD

**Issue by jaagut** [osrf/docker_images#621]
Hi!

When running `sudo apt update` inside a fresh `ros:rolling` container, apt throws the following warning:

```
W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

I hope this issue currently does not affect anything, I just wanted to let you know.

Cheers,
Jan

**Comment by mikaelarguedas** [comment]
Thanks @jaagut for reporting it !

This currently has no effect, this is mostly to notify maintainers that for future versions of ubuntu another way of adding apt repository keys should be used.

---

cc @nuclearsandwich @tfoote @ruffsl 
- I see the official ROS2 instructions get the key from `https://raw.githubusercontent.com/ros/rosdistro/master/`. Would you recommend using that appproach in the docker images as well ? One question I have is about availability, there were sometimes issues with keyservers in the past and I wonder if getting files from githubusercontent is robust in your opinion.
- Do you know where we could fetch the snapshots.ros.org key file from ?

**Comment by nuclearsandwich** [comment]
> * Would you recommend using that appproach in the docker images as well ?

Yeah that is currently the most reliable method for fetching the key we're using for the ROS repositories.
We're working on updating the repository hosts and signing key configurations to support the creation of `ros{,2}{,-testing}-archive-keyring and potentially even ros-snapshots-archive-keyring packages as recommended in https://wiki.debian.org/DebianRepository/UseThirdParty so we can more easily rotate repository signing keys with each distribution as well as move away from the use of deprecated repository configuration methods. I was hoping to get this done for Humble's launch but with everything else going on and a strong desire to be deliberate with keys and get things as right as possible the first time that's been pushed out so we don't rush it.

> Do you know where we could fetch the snapshots.ros.org key file from ?

At this time there is no public https server hosting this key. I'd rather not provide one while the eventual goal is to move toward the archive-keyring packages as it would require changing how we do things twice. If you need stable keys for the Docker images I would suggest embedding the key in the Docker images repository and adding it to the image as a local file. i.e.
```Dockerfile
ADD ros-snapshots.asc /tmp/ros-snapshots.asc
RUN apt-key add /tmp/ros-snapshots.asc && rm /tmp/ros-snapshots.asc
```

**Comment by mikaelarguedas** [comment]
Thanks for the prompt reply!

No rush on our side either as long as the librarians don't require changing the configuration method for submitting new images.
So I'll hold adressing this until the archive keyring is available :+1:

**Comment by icolwell-as** [comment]
I think everyone posting here already understands this, but I wanted to clarify for anyone else that might come across this:

This is also affecting the existing `ros:humble-ros-core` an `ros:humble-ros-base` docker images.
The full output is:
```
W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```
Since it throws an error, this breaks any dockerfiles based on these images with a `RUN apt-get update` instruction in it.

**Comment by mikaelarguedas** [comment]
This is actually unexpected (for example the `ros:humble-ros-base` docker images are based on `ros:humble-ros-core` and doesn't show this problem,
Could you provide a dockerfile to reproduce the problem?

I tried the following Dockerfile but couldn't reproduce the error mentionned above:
```dockerfile
FROM ros:humble-ros-base-jammy

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-perception=0.10.0-1* \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by icolwell-as** [comment]
I am able to trigger the error on both `ros:humble-ros-core` and `ros:humble-ros-base` with the following:

```
docker run -it ros:humble-ros-core
apt update
```

A simple docker file is:
```dockerfile
FROM ros:humble-ros-core

RUN apt-get update
```

Wait, what is the difference between `ros:humble-ros-base-jammy` and `ros:humble-ros-base`? Wouldn't `ros:humble-ros-base`  be based on ubuntu jammy anyway?

**Comment by mikaelarguedas** [comment]
Could you provide more details about your setup (on amd or arm ?), your geographical location etc? as well a providing a full console output?


Here is what I just tried:
<details><summary>apt from within container</summary>
```
mikael@chopper:/tmp/test_apt_issue$ docker run -it ros:humble-ros-core
root@e17d764635e8:/# apt update
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://packages.ros.org/ros2/ubuntu jammy InRelease [4670 B]                       
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]                              
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:6 http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages [564 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [71.8 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4653 B]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [156 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                            
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [155 kB]            
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]                                             
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [268 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [157 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [4653 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [124 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [1202 B]
Fetched 21.8 MB in 4s (6153 kB/s)                
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
root@e17d764635e8:/#
```
</details>

<details><summary>Dockerfile invoking apt</summary>

```bash
mikael@chopper:/tmp/test_apt_issue$ cat Dockerfile 
FROM ros:humble-ros-core

RUN apt-get update
mikael@chopper:/tmp/test_apt_issue$ docker rmi ros:humble-ros-core
Error: No such image: ros:humble-ros-core
mikael@chopper:/tmp/test_apt_issue$ docker pull ros:humble-ros-core
humble-ros-core: Pulling from library/ros
125a6e411906: Already exists 
8b5d137ac3f4: Pull complete 
e7b4f742e0a4: Pull complete 
de85e82a503b: Pull complete 
99d5c725f331: Pull complete 
28ef630c76ed: Pull complete 
315c38decded: Pull complete 
Digest: sha256:27667474549b57bbb4dea8217538cd4e55aa0ef6510cfc8e7e2ae30b7e7c0de6
Status: Downloaded newer image for ros:humble-ros-core
docker.io/library/ros:humble-ros-core
mikael@chopper:/tmp/test_apt_issue$ docker build -t test_apt --no-cache .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ros:humble-ros-core
 ---> 062ff181d64b
Step 2/2 : RUN apt-get update
 ---> Running in e85a91d483bf
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [156 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4653 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [71.8 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [155 kB]
Get:7 http://packages.ros.org/ros2/ubuntu jammy InRelease [4670 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Get:9 http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages [564 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [268 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [124 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [157 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [4653 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [1202 B]
Fetched 21.8 MB in 3s (6512 kB/s)
Reading package lists...
W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Removing intermediate container e85a91d483bf
 ---> 044d49dac640
Successfully built 044d49dac640
Successfully tagged test_apt:latest
```
</details>

**Comment by mikaelarguedas** [comment]
> Wait, what is the difference between ros:humble-ros-base-jammy and ros:humble-ros-base? Wouldn't ros:humble-ros-base be based on ubuntu jammy anyway?

They are identical: https://github.com/osrf/docker_images/blob/d995339f082860f36dfb10d9d86586986095a92a/ros/ros#L136

**Comment by nuclearsandwich** [comment]
@icolwell-as I appreciate that the apt-key warning appears right above the error but your failure appears unrelated and in the future opening a new issue is preferable. It may still be worth it in order to guide future readers to the correct solution.

> `E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'`

What version of Docker are you running on your host system (and what is your Host OS)`.
apt operations can fail in this way on older hosts because they use system calls which are new in the glibc version available in Ubuntu Jammy and thus not part of the default seccomp policy for earlier versions of the Docker engine.

A quick but potentially unsafe way to verify this is to run the container with [`--security-opt seccomp=unconfined`](https://docs.docker.com/engine/security/seccomp/#run-without-the-default-seccomp-profile) and see if you still get the same error.

**Comment by nuclearsandwich** [comment]
https://github.com/osrf/docker_images/issues/621#issuecomment-1138975262 might be the only public artifact from the ROS ecosystem as I got too good at recognizing this type of thing and work on the fixes directly without opening a tracking issue.

**Comment by JuliusSustarevas** [comment]
Seeing this as well on humble-perception. 

THe solution from #623  says it should work wtih Docker >= 20.10.9
But my docker is 20.10.17  and it still doesnt work Im getting same key error
