### ISSUE TITLE
ros_entrypoint.sh incorrectly forwards positional arguments (ROS1)

### ISSUE THREAD

**Issue by h33p** [osrf/docker_images#626]
Try the following:

```
docker run -it --rm ros:melodic bash -h
```

Output:

```
/tmp/setup.sh.fjjyyTaN60: line 1: usage:: command not found
```

It appears that the entire `bash -h` bit gets passed into `/ros/melodic/setup.bash`, since there are no arguments in the source line, and these arguments are then forwarded to _setup_util.py, and specifically the `-h` argument leads to the script to malfunction and output usage information. Editing `ros_entrypoint.sh` as follows seems to solve the issue:

```
#!/bin/bash
set -e

# setup ros environment
args="$@"
set --
source "/opt/ros/$ROS_DISTRO/setup.bash"
exec $args
```

**Comment by ruffsl** [comment]
Interesting find. My shell foo isn't familiar with all the ramifications of such a subtle but significant change to our entrypoint.

Perhaps I could get some second opinions?
CC @tfoote @nuclearsandwich @mikaelarguedas @yosifkit @tianon

For comparison, here is the current default entrypoint:

https://github.com/osrf/docker_images/blob/c5d0709fd289e516a1c501c2120fcf1c08da6fd8/ros/rolling/ubuntu/jammy/ros-core/ros_entrypoint.sh#L1-L6

**Comment by tfoote** [comment]
Appending `--` looks like a great way to resolve this.
