### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by cadmus-to** [osrf/docker_images#632]
This might have been something a bit more meaningful but these types of links in the README probably do not go where it was intended to. E.g. https://microbadger.com/#/images/library/ros

**Comment by ruffsl** [comment]
Yea, I think those links use to map to a site that would vizualize all dockerimage layers and respective sizes and parent images.  
Perhaps there is a sucsessor, else we can strip those kind of hyperlings completly.

**Comment by karlis-ozo** [comment]
@ruffsl, I would advise to get those links deleted from the README!
They currently lead to advertising site that is not related to ROS or docker and it's contents are questionable at best.

**Comment by JHartzer** [comment]
Howdy @ruffsl, I don't believe this change was pushed to docker hub which still has the offending broken links https://hub.docker.com/r/osrf/ros2.

**Comment by ruffsl** [comment]
Thanks @JHartzer , those READMEs use to automatically mirror the repo's back when we still used Docker Hub's automated builds. With that being deprecated in favor of GitHub actions, those must have never been updated. I've cut them down to just redirect to the GitHub repo directly.
