### ISSUE TITLE
ROS 2 nightly seems to embed wrong version of flake8

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [osrf/docker_images#640]
The ROS 2 nightly docker image seems to be embedding the wrong version of `flake8`.

`flake8` is [installed with PIP3](https://github.com/osrf/docker_images/blob/master/ros2/nightly/nightly/Dockerfile#L50) in the [version 5.0.4](https://pypi.org/project/flake8/).

The flake8 package [available from APT is the version 4.0.1](https://packages.ubuntu.com/jammy/python3-flake8). This package is a dependency of the [python3-ament-cmake](https://packages.ubuntu.com/jammy/python3-ament-flake8).

The package from rolling `ament-lint` doesn't support flake8 5.0.4 since [it's using the option `prog` from the `OptionManager`](https://github.com/ament/ament_lint/blob/rolling/ament_flake8/ament_flake8/main.py#L177:L200) that exist in the [4.0.1](https://github.com/PyCQA/flake8/blob/4.0.1/src/flake8/options/manager.py#L350) but no longer in the [5.0.4](https://github.com/PyCQA/flake8/blob/5.0.4/src/flake8/options/manager.py#L318).

This cause `ament-lint` to crash because it's setting the option `prog` that doesn't exist.

Why is flake8 installed from PIP?
Should the PIP install of `flake8` be removed from the docker image?
(I noticed the same problem with the PIP package `pycodestyle`)

---
To reproduce:
`docker run -ti osrf/ros2:nightly bash`
`mkdir -p ws/src`
`cd ws/src`
`git clone https://github.com/ros2/demos.git`
`cd ../`
`rosdep update`
`rosdep install --from-paths src --ignore-src --rosdistro rolling -y`
`colcon build --event-handlers console_cohesion+ --packages-select topic_monitor`
`colcon test --packages-select topic_monitor --return-code-on-test-failure --event-handlers console_cohesion+`
error: 
```
Starting >>> topic_monitor
--- output: topic_monitor
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /r2_ws/build/topic_monitor/.pytest_cache
rootdir: /r2_ws/src/demos, configfile: pytest.ini
plugins: launch-testing-ros-0.21.0, ament-pep257-0.13.2, ament-flake8-0.13.2, ament-xmllint-0.13.2, launch-testing-1.2.0, ament-lint-0.13.2, ament-copyright-0.13.2, launch-pytest-1.2.0, ament-mypy-0.13.2, repeat-0.9.1, rerunfailures-10.2, mock-3.6.1, timeout-2.1.0, cov-3.0.0, colcon-core-0.10.0
collecting ...
collected 2 items

test/test_flake8.py F                                                    [ 50%]
test/test_pep257.py .                                                    [100%]

=================================== FAILURES ===================================
_________________________________ test_flake8 __________________________________
/opt/ros/rolling/lib/python3.10/site-packages/ament_flake8/main.py:182: in parse_config_file
    opts_manager = manager.OptionManager(prog='flake8', version='4.0.0')
E   TypeError: OptionManager.__init__() got an unexpected keyword argument 'prog'

During handling of the above exception, another exception occurred:
test/test_flake8.py:22: in test_flake8
    rc, errors = main_with_errors(argv=[])
/opt/ros/rolling/lib/python3.10/site-packages/ament_flake8/main.py:88: in main_with_errors
    report = generate_flake8_report(
/opt/ros/rolling/lib/python3.10/site-packages/ament_flake8/main.py:202: in generate_flake8_report
    opts, _ = parse_config_file(config_file)
/opt/ros/rolling/lib/python3.10/site-packages/ament_flake8/main.py:191: in parse_config_file
    opts_manager = manager.OptionManager(prog='flake8', version='3.0.0')
E   TypeError: OptionManager.__init__() got an unexpected keyword argument 'prog'
---------- generated xml file: /r2_ws/build/topic_monitor/pytest.xml -----------
=========================== short test summary info ============================
FAILED test/test_flake8.py::test_flake8 - TypeError: OptionManager.__init__()...
========================= 1 failed, 1 passed in 0.20s ==========================
---
Finished <<< topic_monitor [1.02s]      [ with test failures ]

Summary: 1 package finished [1.24s]
  1 package had test failures: topic_monitor
```

**Comment by mikaelarguedas** [comment]
Thanks for reporting

It's likely due to the fact that historically flake8 and related plugins were installed from pip for ROS 2 but apparently since recently https://github.com/ros-infrastructure/rep/pull/355#discussion_r910227721 the packages are available from apt but most developers and packages use the pip version.

On one hand ament_flake8 should be compatible with both: https://github.com/ament/ament_lint/issues/399
On the other hand we should look to install differently in the docker images for nightly to match what the ROS buildfarm does

**Comment by mikaelarguedas** [comment]
@Guillaumebeuzeboc https://github.com/osrf/docker_images/pull/641 should fix the issue if you want to try it before it hits dockerhub

**Comment by Guillaumebeuzeboc** [comment]
I just tested, and I can confirm that the problem is fixed with this change
