### ISSUE TITLE
Update Humble images?

### ISSUE THREAD

**Issue by audrow** [osrf/docker_images#648]
Should the Humble images be built regularly? It seems that they haven't been built in a month or so. I have made a patch release to Humble since the last update. 

![Screenshot 2022-12-07 at 9 38 48 AM](https://user-images.githubusercontent.com/6635382/206223121-cb2f7cb1-083e-4635-83f2-dd59bb8cbb9f.png)

This was brought up here: https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2022-11-23/28495/2?u=audrow

**Comment by sloretz** [comment]
https://github.com/osrf/docker_images/issues/112 - latest state: https://github.com/osrf/docker_images/issues/112#issuecomment-902952671

The short answer is there isn't currently a way to rebuild them after a patch release. They only get rebuilt when their base image does.

**Comment by mikaelarguedas** [comment]
humble images are now up to date following ubuntu images update.

Closing as immediate issue addressed and long term issue tracked in #112
