### ISSUE TITLE
Is it possible to rebuild official docker image ros:rolling?

### ISSUE THREAD

**Issue by hodnajit** [osrf/docker_images#654]
Hi,

I am facing some issues with the newest released packages for ros:rolling in the docker image and updating the docker image would fix that.

Steps to reproduce the issue:

I run the official ros:rolling image
`docker run -it ros:rolling`

I run apt update && upgrade
`apt-get update && apt-get upgrade

and the result is, that

```
The following packages have been kept back:
  ros-rolling-rosbag2-storage-default-plugins
```

But without this package, I cannot play rosbags successfully and get a segmentation fault.

If I run 
`apt install ros-rolling-rosbag2-storage-default-plugins`

Everything is installed successfully and everything works.

What do you think?

**Comment by rshanor** [comment]
I too am having issues with the `rolling-ros-core-jammy` docker images. It looks like it was last built ~1 month ago and I am having some linking issues with the image transport package.

https://hub.docker.com/layers/library/ros/rolling-ros-core-jammy/images/sha256-8649d3ff11624e61eb7c7010fc0f186f21cd8e4a0ad1d2c27c9a39dc8a59987d?context=explore

**Comment by mikaelarguedas** [comment]
Unfortunately today the rebuild of the images in the official docker library are bound to the rebuild of the base image.
Usually the ubuntu base images are rebuilt once a month as [the last jammy update was a month ago](https://hub.docker.com/_/ubuntu/tags?page=1&name=jammy) it should happen shorty

c.f. https://github.com/osrf/docker_images/issues/648#issuecomment-1341179283
