### ISSUE TITLE
How to run ROS2 hello-world (talker-listener) on raspberry PI (arm arch)?

### ISSUE THREAD

**Issue by fghoussen** [osrf/docker_images#655]
How to run ROS2 hello-world (talker-listener) on raspberry PI (arm arch)?

Googling is no easy as one found lots of different/contradictory things out there!... 

Following this https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html takes forever (several hours - I had to ctrl-C the build).

Then, looking for docker precompiled image, I found https://hub.docker.com/r/osrf/ros2/ and gave a try to `sudo docker pull osrf/ros2:devel`... But looks like it get amd64 images which can not be ran on arm (raspberry pi)

Then, googling, finally found https://docs.ros.org/en/foxy/How-To-Guides/Installing-on-Raspberry-Pi.html, then gave a try to `git clone  https://github.com/osrf/docker_images && cd docker_images/docker && docker build -t ros_docker .`, but then, running ` sudo docker run -it --rm --mount type=bind,source=/path/to/home,target=/home ros_docker /bin/bash` in the terminal no way to find any .bash file to run `. ~/ros2_rolling/install/local_setup.bash &&
ros2 run demo_nodes_cpp talker`

Can someone describe the recommended steps to follow on raspberry pi to run the ROS2 hello world (talker-listener), or, point at an updated doc?

Thanks

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Though before you ask there. i would suggest that you make sure that you understand how to run docker images on your raspberry Pi generically(with the different default arches etc) before you try to run the ROS images. There's a lot of general docker information on that and is likely not best to ask in a ROS specific forum..
