### ISSUE TITLE
base and core images are missing

### ISSUE THREAD

**Issue by ijnek** [osrf/docker_images#672]
It's been a few weeks since I've used the base and core images for ROS 2 distros, but they seem missing.

```sh
docker run -it osrf/ros:rolling-ros-base
```

can't find an image. What happened to the base and core images?

**Comment by mikaelarguedas** [comment]
The base and core images for ROS 1 and ROS2 distros are part of the [official docker library](https://hub.docker.com/_/ros)

```
docker run -it ros:rolling-ros-base
```

Happy containing

**Comment by ijnek** [comment]
Oh, yes. I tend to get quite confused about these docker repos. Thanks @mikaelarguedas
