### ISSUE TITLE
[Question]bash: ros2: command not found

### ISSUE THREAD

**Issue by badguyisme** [osrf/docker_images#693]
Hi, I pull and run the docker image osrf/ros:humble-desktop-full successfully. When I input ros2 command in the container, everything seems ok
![image](https://github.com/osrf/docker_images/assets/122729626/ed806f6d-3dc6-41e6-bf99-9d4578e215d4)

However, when I open another terminal and using docker exec command to reach the same container, bash cannot find command ros2.
![image](https://github.com/osrf/docker_images/assets/122729626/597991ff-701e-4ec3-89cd-8cc62614dd38)

Why is this happening? Hope to be answered, thank you!

**Comment by mikaelarguedas** [comment]
Indeed, you need to source the ROS environment to have access to the ROS tools:
```
source /opt/ros/humble/setup.bash
```
The entrypoint is only executed when starting the container not when logging into it: https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by badguyisme** [comment]
It works. Thanks for your helping.
