### ISSUE TITLE
Raspberry PI 4b 64-bit OS issues

### ISSUE THREAD

**Issue by knmcguire** [osrf/docker_images#703]
Hi! I am already planning to install ubuntu on my Raspberry PI 4b already, but before I do that I'd like to notify you of some issues I had trying the ROS docker images on the RPI with the Raspberry Pi OS (the lite version) when I followed this [official ROS2 documentation](https://docs.ros.org/en/humble/How-To-Guides/Installing-on-Raspberry-Pi.html#ubuntu-linux-on-raspberry-pi-with-binary-ros-2-install).

First I wanted to grab the prebuild docker images, but when running it I ran into this:
```
$ docker run -it osrf/ros:humble-desktop-full
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /ros_entrypoint.sh: exec format error
```

I found [this fix](https://stackoverflow.com/questions/60725360/problem-when-running-docker-image-roskinetic-standard-init-linux-go211-exec) that I wanted to try out when building the image source itself, but before I could even try that Iran into the following error when I tried to build the repo (clean so without the fix).
```
$ docker build -t ros_docker .
[+] Building 0.1s (2/2) FINISHED                                                       docker:default
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 2B                                                               0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1556807727/Dockerfile: no such file or directory
```

Note again, I will install ubuntu on the RPi as this is probably more ideal, but I just wanted to note these issues as these occurred when I was following the steps of the official documentation.

**Comment by mikaelarguedas** [comment]
Thanks for your feedback.

The support for multiple architectures build is currently only available for the images hosted in the official docker library (the images starting with ros:xxx. You can refer to the [architectures section on the README](https://github.com/osrf/docker_images#architectures)

The build for other platforms is not available on the OSRF profile (thi images with `osrf/ros:xxx` (so the images that include GUI like desktop and desktop-full), c.f. [this section of the README](https://github.com/osrf/docker_images#architectures-2).

Happy containing

**Comment by mikaelarguedas** [comment]
Regarding the building on RaspberryPi OS, I do not have the hardware to try it out ATM (and I'll be honest I was not aware of these docs section that likely need to be updated).

Could you give a bit mmore details here about how your build went:
- Without the fix mentionnend on SlackOverflow:
  - Could you build the ros-core image?
  - If not what errors did you face?

Thanks!

**Comment by knmcguire** [comment]
ah sorry there were some parts that weren't clear in my original post:

- I wanted to run the ROS-desktop docker image from the official OSRF docker hub on my raspberry PI 4B that is running Raspberry pi OS lite
- The errors I mentioned above was before I tried the fix at all, so with the clean clone of the docker_images repo

**Comment by mikaelarguedas** [comment]
> I wanted to run the ROS-desktop docker image from the official OSRF docker hub on my raspberry PI 4B that is running Raspberry pi OS lite

So you will indeed need to build the image yourself as the desktop image is not part of the [official docker library](https://hub.docker.com/_/ros/tags) (it is part of the [OSRF dockerhub](https://hub.docker.com/u/osrf/)) so it does exist only for amd64 architecture

> The errors I mentioned above was before I tried the fix at all, so with the clean clone of the docker_images repo

Got it, and after the fix did you succeed to build or did you have other errors ?

**Comment by knmcguire** [comment]
1- Got it. That wasn't clear from the documentation indeed.
2- ah no it was the same error, it didn't reach the fix as that was meant for the first error I got which is unrelated as it seems

**Comment by mikaelarguedas** [comment]
I got my hands on a RaspberryPi 4B and tried this:

- Installed [ubuntu 22.04 desktop image for raspberrypi](https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04.3&architecture=desktop-arm64+raspi)
- uncommented [these lines](https://github.com/osrf/docker_images/blob/119525d96b79c069e6a60314ac140530ea564587/ros/humble/ubuntu/jammy/Makefile#L17-L18)
- `make build`

And all the images built successfully
- launched a talker / listener demo: `ros2 launch demo_nodes_cpp talker_listener.launch.xml`
- It launched ands ran successfully

**Comment by knmcguire** [comment]
Hi! The issues I had was with  [Raspberry Pi OS Lite](https://www.raspberrypi.com/software/operating-systems/), not with the Ubuntu desktop image for raspberry pi.  I was about to switch to the latter due to the issues I had with the PI OS but wanted to at least report the issues I had with when I followed [this part of the documentation  ](https://docs.ros.org/en/humble/How-To-Guides/Installing-on-Raspberry-Pi.html#raspberry-pi-os-with-ros-2-in-docker) step by step. 

But it is good to know that it does seem the work on the ubuntu desktop version, which will make it easier for me to justify the switch.

**Comment by mikaelarguedas** [comment]
> Hi! The issues I had was with [Raspberry Pi OS Lite](https://www.raspberrypi.com/software/operating-systems/),

> Note again, I will install ubuntu on the RPi as this is probably more ideal

It was mostly to let you know that you will likely not face that issue on Ubuntu

**Comment by mikaelarguedas** [comment]
Today I tried on RaspberryPi OS:

- raspberryPi 4B
- RaspberryPi OS 12(bookworm) desktop version (I'll give a shot to the lite version when I get a chance)

```bash
sudo apt update && sudo apt install -y git
cd /tmp
git clone https://github.com/osrf/docker_images
cd docker_images/ros/humble/ubuntu/jammy/
```
Edit the Makefile to uncomment the docker build commands for desktop and destkop full

```bash
sudo make build
```

It built all docker images successfully and I could run them and launch a talker listener demo

**Comment by mikaelarguedas** [comment]
Same result with the lite version of raspbian 12.

I could build and run images without issue.

Waiting to get more feedback on this issue but if none provided in the coming weeks I'm inclined to close this

**Comment by knmcguire** [comment]
Ah okay, thanks that you have checked raspbians as well. Since I've already moved to Ubuntu 22.04 and used up my last SD card for that. I'll try to find a reserve but since it seems I'll be busier than planned and traveling the coming weeks to test this, it is fine if you'd close this. You have tested it with raspbian 12 both versions also on a raspberry pi 4b and weren't able to recreate my situation. Since no-one has come forward with the same problem there is probably not a high risk in that. Most likely next time I try it it should work for me as well I'm sure

Thanks again for your help of testing this out.

**Comment by mikaelarguedas** [comment]
Closing for now, dont hesitate to comment if you face this issue and we can reopen
