### ISSUE TITLE
colcon build without --symlink install

### ISSUE THREAD

**Issue by elgarbe** [osrf/docker_images#724]
I'm wondering why you use[ symlink install](https://github.com/osrf/docker_images/blob/3d7df313d1b9be171f5aa87b5daa097354f753ea/ros2/source/source/Dockerfile#L32)?

Don't be better use just colcon build and then remove log, build and src?

**Comment by tfoote** [comment]
This is reproducing the default source installation instructions: https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html

The symlink install enables quicker iterations for scripting development. https://robotics.stackexchange.com/questions/98303/what-is-the-use-of-symlink-install-in-ros2-colcon-build

If you have more questions please ask on robotics.stackexchange.com
