### ISSUE TITLE
Update ubuntu base to noble for Rolling

### ISSUE THREAD

**Issue by Yadunund** [osrf/docker_images#728]
Rolling has migrated to Ubuntu Noble: https://discourse.ros.org/t/preparing-ros-2-rolling-for-the-transition-to-ubuntu-24-04/35673/16

**Comment by mikaelarguedas** [comment]
I was mislead by that discourse post as well. But the migration is not done yet and multiple variants like simulation and desktop-full [are not available yet](http://repo.ros2.org/status_page/ros_rolling_default.html?q=variant) preventing the generation and release of the docker images. Same thing for the nightly buildfs that are still not targetting rolling (https://ci.ros2.org/job/ci_packaging_linux/)

Hopefully the migration of the main part of ROS (the official variants) will be completed soon !

**Comment by Yadunund** [comment]
Sounds good. Thanks @mikaelarguedas!

**Comment by MartinPeris** [comment]
I am interested in having this working, can I help?

**Comment by ruffsl** [comment]
@mikaelarguedas , from the repo.ros2.org/status_page/ , it looks like core, base, and perception meta packages are now available. Perhaps we could cut a release for just the official library images that only include those tags anyhow? Not sure when desktop and simulation meta packages will ever arrive.

**Comment by mikaelarguedas** [comment]
> from the repo.ros2.org/status_page/ , it looks like core, base, and perception meta packages are now available

Yes, the situation has been the same since https://github.com/osrf/docker_images/issues/728#issuecomment-2002103668, I originally assumed it would be a matter of days. I haven't found any information on the status / progress so I asked here https://discourse.ros.org/t/preparing-ros-2-rolling-for-the-transition-to-ubuntu-24-04/35673/17

> Perhaps we could cut a release for just the official library images that only include those tags anyhow?

Agreed, I tweaked the feature branch accordingly and opened https://github.com/osrf/docker_images/pull/731

I'll move forward and see to get that upstream and we'll update as needed

**Comment by luca-della-vedova** [comment]
Thanks for all the great work! I believe (since the Jazzy image for desktop-full and simulation was released) that there should be no more blockers now to release the remaining `simulation` and `desktop-full` for Rolling on Noble, if that's the case is anyone working on it yet>

**Comment by mikaelarguedas** [comment]
This is currently waiting for the rolling sync.
https://github.com/osrf/docker_images/pull/742#issuecomment-2087567062

Apparently rolling was synced to main just before the `simulation` and `desktop-full` packages were fixed so now we need to wait for the next one...
