### ISSUE TITLE
qt.qpa.xcb: could not connect to display :1

### ISSUE THREAD

**Issue by fabriros** [osrf/docker_images#740]
### Description:
I have tried to execute ros in a docker container on vscode. I have followed the tutorial at [this page](https://docs.ros.org/en/humble/How-To-Guides/Setup-ROS-2-with-VSCode-and-Docker-Container.html) .
I have a problem in visualizing rviz2.
### Environment:
* ROS Distro: Humble
* OS Version: Ubuntu 22.04

### Expected behaviour
Open rviz2 through vscode
### Actual behaviour
Error:
`qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted`

### My files
[devcontainer.json](https://github.com/osrf/docker_images/files/15162003/devcontainer.json)
Docker file:
![Screenshot from 2024-04-30 12-35-48](https://github.com/osrf/docker_images/assets/164006102/b5129e3e-081b-4a0c-aa7a-c14c302583bc)

Thank you in advance!

**Comment by ahcorde** [comment]
Try to run before you launch the docker container: `xhost local:root`

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site. You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

**Comment by DaveCollinsJr** [comment]
Running the xhost local:root command locally before I built the container solved this problem for me.
> Try to run before you launch the docker container: xhost local:root
