### ISSUE TITLE
Archiving of legacy ROS distros

### ISSUE THREAD

**Issue by ruffsl** [osrf/docker_images#80]
We've recently introduced docker images for all previous ROS releases, going way back to boxturtle, all of which have also reached end of life, including the upstream base images of ubuntu they build `FROM`, i.e. 10.04 and 12.04. These images should be beneficial for anyone who needs to research and run  ROS code from previous published literature or archives to port legacy packages or reproduce results.

Currently these images are being housed under `osrf/ros_eol` automated repo on docker hub, but there is the question if this is the best place to archive them. Specifically, having separate repos for distros Before LTS (I'll just call this legacy for short), the first LTS being indigo, seem somewhat inconsistent.

This relates a little to issue https://github.com/osrf/docker_images/issues/79, with the specific question here being if it would be possible to also archive these legacy images alongside the rest of releases on the library/ros repo. So that users want to access legacy images could just as simply refer to `FROM ros/boxturtle`. These dockerfile are not expected to change, so we could simple add them then remove the from the build manifest to push them into the official library archive, but I'm not sure if this is a direction the library maintainers would OK.

pringing: @mikaelarguedas @tfoote @j-rivero @tianon @yosifkit

**Comment by yosifkit** [comment]
If it was a few month ago I would have said yes to back-filling old versions based on unsupported Ubuntu images. Unfortunately, the new multi-arch system would be unable to build the images since there is no architecture specific images for 10.04 and 12.04 (ie `amd64/ubuntu:10.04`).

**Comment by ruffsl** [comment]
@yosifkit , couldn't we get around that by first pushing `library/ubuntu:10.04` to `amd64/ubuntu:10.04` before back-filling old ros images with the multi-arch manifest?

**Comment by tianon** [comment]
Ubuntu 10.04 is anciently deprecated at this point, and I'd really rather
avoid spending any effort doing anything at all with it. 😉

**Comment by ruffsl** [comment]
Ok, hmm... one last idea, then I'll concede to just hosting the legacy images under say osrf/<> 

What if we just one-time PR'ed a manifest in the old format that included the legacy ROS tags, pushing them into the archive of the official registry, then reverted the manifest commit back? Are old manifest formats still dealt with the new multi-arch system?

**Comment by yosifkit** [comment]
The old format is only supported on disk and treated the same once it is read by the bashbrew tool.

**Comment by ruffsl** [comment]
Well, given the legacy images are new and could still receive PRs from the community, perhaps it would be best to host them under osrf/<> so that they can updated with contributions. @tfoote ?

**Comment by mikaelarguedas** [comment]
@ruffsl There seem that both `ros_legacy` and `ros_eol` repositories are active and building images. 
Can we delete/(or at least disable builds) for the `ros_eol` one?

**Comment by ruffsl** [comment]
I think we could delete `ros_eol` to avoid confusion. Yet it seems to have a larger pull count, so we may want to make a reminder announcement on discourse as to which reopo should be used.
